# Introduction

The UK railway industry works on a system where it is operated by a number of organisations. Passenger and freight services are operated by Train Operating Companies (TOC's), while the infrastructure is run by Network Rail.

In the past few years the state of the UK rail industry has been affected by COVID-19, and the Government policies implemented during this time. COVID-19 has changed the way the public view rail, as well as the way that TOCs operate.

What are considered the key parameters for a TOC?

Has key metrics reached the same levels pre and post-COVID-19?

How have passengers reacted to rail usage, compared to reaction to TOCs operations?

Has COVID-19 changed the status of the biggest and smallest TOCs?

What are the immediate trends for the future of the UK rail industry?

The scope of this project looks at data before and after COVID-19, encompassing the years 2017-2023. The project will look at the trends of all of the TOCs combined while providing data visualisation to the trends for each TOC.



# Table of contents

1. Sourcing the data
2. Data cleaning
3. Exploratory Data Analysis
4. Data Visualisation
5. Conclusions



# Sourcing the data

The data is provided by the Office of Rail and Road data portal

## Import Statements

In [5]:
%pip install --upgrade plotly
%pip install odfpy


     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.6/15.6 MB 34.7 MB/s eta 0:00:00
  Attempting uninstall: plotly
    Found existing installation: plotly 5.15.0
    Uninstalling plotly-5.15.0:
      Successfully uninstalled plotly-5.15.0
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 717.0/717.0 kB 5.8 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
  Created wheel for odfpy: filename=odfpy-1.4.1-py2.py3-none-any.whl size=160672 sha256=1af08aee11f2c24f421a413e34d9966c14d42df0062da868e45a55d16bc18b68
  Stored in directory: /root/.cache/pip/wheels/c8/2e/95/90d94fe33903786937f3b8c33dd88807f792359c6424b40469
Successfully built odfpy


In [6]:
import numpy as np
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import seaborn as sns


## Loading the Data

We are loading two tables: Data from 2018-2022 and data from 2019-2023. The objective is to get a dataset with a range of 2018-2023. This will shows us data before, during, and after COVID-19.

In [7]:
raw_key_stats_data = pd.read_excel("2200_key_statistics_by_operator.ods", "2200_Key_statistics_by_operator", engine="odf")

In [8]:
raw_key_stats_data_2 = pd.read_excel("table-2200_key_statistics_by_operator_2.ods", "2200_Key_statistics_by_operator", engine="odf")

In [9]:

raw_key_stats_data.head()

Table 2200: Train operating company key statistics by operator, Great Britain, April 2017 to March 2022  \
0  This worksheet contains four tables presented ...                                                        
1  Some cells refer to notes which can be found o...                                                        
2  Some shorthand is used in this table, [b] = br...                                                        
3           Table 2200a: Key statistics, annual data                                                        
4                                        Time period                                                        

  Unnamed: 1         Unnamed: 2 Unnamed: 3          Unnamed: 4  \
0        NaN                NaN        NaN                 NaN   
1        NaN                NaN        NaN                 NaN   
2        NaN                NaN        NaN                 NaN   
3        NaN                NaN        NaN                 NaN   
4    Measure  Avanti West Coast        c2c  Caledonian Sleeper   

          Unnamed: 5    Unnamed: 6             Unnamed: 7  \
0                NaN           NaN                    NaN   
1                NaN           NaN                    NaN   
2                NaN           NaN                    NaN   
3                NaN           NaN                    NaN   
4  Chiltern Railways  CrossCountry  East Midlands Railway   

                 Unnamed: 8     Unnamed: 9  ...    Unnamed: 16 Unnamed: 17  \
0                       NaN            NaN  ...            NaN         NaN   
1                       NaN            NaN  ...            NaN         NaN   
2                       NaN            NaN  ...            NaN         NaN   
3                       NaN            NaN  ...            NaN         NaN   
4  Govia Thameslink Railway  Grand Central  ...  Lumo [note 1]  Merseyrail   

       Unnamed: 18 Unnamed: 19            Unnamed: 20   Unnamed: 21  \
0              NaN         NaN                    NaN           NaN   
1              NaN         NaN                    NaN           NaN   
2              NaN         NaN                    NaN           NaN   
3              NaN         NaN                    NaN           NaN   
4  Northern Trains    ScotRail  South Western Railway  Southeastern   

  Unnamed: 22 Unnamed: 23           Unnamed: 24           Unnamed: 25  
0         NaN         NaN                   NaN                   NaN  
1         NaN         NaN                   NaN                   NaN  
2         NaN         NaN                   NaN                   NaN  
3         NaN         NaN                   NaN                   NaN  
4    TfL Rail    TfW Rail  TransPennine Express  West Midlands Trains  

[5 rows x 26 columns]

In [10]:
raw_key_stats_data_2.head()

Table 2200: Train operating company key statistics by operator, Great Britain, April 2018 to March 2023  \
0  This worksheet contains four tables presented ...                                                        
1  Some cells refer to notes which can be found o...                                                        
2  Some shorthand is used in this table, [b] = br...                                                        
3           Table 2200a: Key statistics, annual data                                                        
4                                        Time period                                                        

  Unnamed: 1         Unnamed: 2 Unnamed: 3          Unnamed: 4  \
0        NaN                NaN        NaN                 NaN   
1        NaN                NaN        NaN                 NaN   
2        NaN                NaN        NaN                 NaN   
3        NaN                NaN        NaN                 NaN   
4    Measure  Avanti West Coast        c2c  Caledonian Sleeper   

          Unnamed: 5    Unnamed: 6             Unnamed: 7  \
0                NaN           NaN                    NaN   
1                NaN           NaN                    NaN   
2                NaN           NaN                    NaN   
3                NaN           NaN                    NaN   
4  Chiltern Railways  CrossCountry  East Midlands Railway   

                Unnamed: 8                Unnamed: 9  ...        Unnamed: 16  \
0                      NaN                       NaN  ...                NaN   
1                      NaN                       NaN  ...                NaN   
2                      NaN                       NaN  ...                NaN   
3                      NaN                       NaN  ...                NaN   
4  Elizabeth line [note 2]  Govia Thameslink Railway  ...  London Overground   

     Unnamed: 17 Unnamed: 18      Unnamed: 19 Unnamed: 20  \
0            NaN         NaN              NaN         NaN   
1            NaN         NaN              NaN         NaN   
2            NaN         NaN              NaN         NaN   
3            NaN         NaN              NaN         NaN   
4  Lumo [note 1]  Merseyrail  Northern Trains    ScotRail   

             Unnamed: 21   Unnamed: 22 Unnamed: 23           Unnamed: 24  \
0                    NaN           NaN         NaN                   NaN   
1                    NaN           NaN         NaN                   NaN   
2                    NaN           NaN         NaN                   NaN   
3                    NaN           NaN         NaN                   NaN   
4  South Western Railway  Southeastern    TfW Rail  TransPennine Express   

            Unnamed: 25  
0                   NaN  
1                   NaN  
2                   NaN  
3                   NaN  
4  West Midlands Trains  

[5 rows x 26 columns]

We now combine the two datasets into a larger one, while removing some junk data.

In [ ]:
raw_datasets = [raw_key_stats_data, raw_key_stats_data_2]
for dataset in raw_datasets:
  dataset.columns = dataset.iloc[4]
  dataset = dataset.drop(dataset.index[0:5])
  dataset = dataset.replace(to_replace=r"\[r]", value=None, regex=True)
  dataset = dataset.replace(to_replace=r"\[b]", value=None, regex=True)
  dataset = dataset.replace(to_replace=r"\[z]", value=None, regex=True)
  dataset = dataset.replace(to_replace=r"\[x]", value=None, regex=True)
raw_data = pd.concat(raw_datasets)
raw_data = raw_data.rename_axis(None, axis=1)

The original files have multiple tables on the same sheet.

The sheets have four tables:
1. Key Statistics, annual data
2. Passenger experience, annual data
3. Punctuality and reliability, annual data
4. Delay minutes, annual data


These tables have sub-tables, which contain the information we want.

# Data extraction and cleaning

The two original datasets have different names for the same category. For example, "Delays-NR-on_TOC" and "Network Rail on TOC delays (minutes)" mean the same thing.

Furthermore, the raw_data has "Measure" as a Measure. These rows should be removed.


In [ ]:
raw_data["Measure"].value_counts()

Cancellations score (percentage)         10
Trains planned                           10
Number of stations managed               10
Passenger journeys (millions)            10
Passenger kilometres (millions)          10
Passenger train kilometres (millions)    10
Route kilometres operated                10
Complaints closed                        10
Passenger assists                        10
Full-time equivalent (FTE) employees     10
Delay compensation claims closed          9
Measure                                   8
On Time                                   5
Delays-NR-on-TOC                          5
Delays-TOC-on-Self                        5
Delays-TOC-on-TOC                         5
On Time (percentage)                      5
Network Rail on TOC delays (minutes)      5
TOC on self delays (minutes)              5
TOC on TOC delays (minutes)               5
Name: Measure, dtype: int64

In [ ]:
raw_data = raw_data[raw_data["Measure"] != "Measure"]
raw_data = raw_data.dropna(subset=['Measure'])

In [ ]:
raw_data["Measure"] = raw_data["Measure"].replace({
    "Delays-NR-on-TOC": "Network Rail on TOC delays (minutes)",
    "Delays-TOC-on-Self": "TOC on self delays (minutes)",
    "Delays-TOC-on-TOC": "TOC on TOC delays (minutes)",
    "On Time": "On Time (percentage)",
    },
                            regex=True)

raw_data["Measure"] = raw_data["Measure"].replace({
    "On Time \(percentage\) \(percentage\)": "On Time (percentage)",
    },
                            regex=True)

raw_data["Measure"] = raw_data["Measure"].replace({
    r"On Time \[.*\]": "",
    },
                            regex=True)

raw_data = raw_data.replace({r" \[.*\]": "", r"\[.*]": np.nan, r"As at": "As of"}, regex=True)

In [ ]:
raw_data["Measure"].value_counts()

Full-time equivalent (FTE) employees     10
Number of stations managed               10
Passenger journeys (millions)            10
Passenger kilometres (millions)          10
Passenger train kilometres (millions)    10
Route kilometres operated                10
Complaints closed                        10
Passenger assists                        10
Cancellations score (percentage)         10
Trains planned                           10
On Time (percentage)                     10
Network Rail on TOC delays (minutes)     10
TOC on self delays (minutes)             10
TOC on TOC delays (minutes)              10
Delay compensation claims closed          9
Name: Measure, dtype: int64

In [ ]:
raw_data = raw_data.rename(columns={"Lumo [note 1]": "Lumo", "TfL Rail": "Elizabeth line 1"})
raw_data["Elizabeth line"] = raw_data["Elizabeth line 1"].fillna(raw_data["Elizabeth line [note 2]"])
raw_data = raw_data.drop(columns=['Elizabeth line 1', 'Elizabeth line [note 2]'])

In [ ]:
raw_data["Time period"] = raw_data["Time period"].str.strip()

In [ ]:
data_tables = {}
for measure in raw_data["Measure"].value_counts().index:
  data_tables[measure] = raw_data[raw_data["Measure"] == measure]
  data_tables[measure] = data_tables[measure].drop_duplicates("Time period", keep="last").reset_index(drop=True)
  data_tables[measure] = data_tables[measure].drop('Measure', axis=1)
  data_tables[measure] = data_tables[measure].set_index("Time period")

# Exploratory Data Analysis

## Who are the TOC's?

TOC stands for Train Operating Company.

In [ ]:
raw_data.columns

Index(['Time period', 'Measure', 'Avanti West Coast', 'c2c',
       'Caledonian Sleeper', 'Chiltern Railways', 'CrossCountry',
       'East Midlands Railway', 'Govia Thameslink Railway', 'Grand Central',
       'Great Western Railway', 'Greater Anglia', 'Heathrow Express',
       'Hull Trains', 'London North Eastern Railway', 'London Overground',
       'Lumo', 'Merseyrail', 'Northern Trains', 'ScotRail',
       'South Western Railway', 'Southeastern', 'TfW Rail',
       'TransPennine Express', 'West Midlands Trains', 'Elizabeth line'],
      dtype='object')

"Time period" and "Measure" aside, the columns of the raw data show the names of the TOC's.

## Full-time equivalent (FTE) employees

In [ ]:
full_time_employees = data_tables["Full-time equivalent (FTE) employees"]
full_time_employees.head()

Avanti West Coast     c2c  Caledonian Sleeper  \
Time period                                                          
As of 31 March 2018           3581.000  682.00               168.0   
As of 31 March 2019           3724.000  690.00               174.0   
As of 31 March 2020           3383.310  642.70               195.0   
As of 31 March 2021           3326.000  647.76               184.0   
As of 31 March 2022           3278.647  633.40               187.0   

                     Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                   
As of 31 March 2018              840.0        1885.0                2352.00   
As of 31 March 2019              852.0        1915.0                2460.00   
As of 31 March 2020              850.0        1983.0                2440.50   
As of 31 March 2021              850.0        1961.0                2504.11   
As of 31 March 2022              895.5        1913.6                2294.00   

                     Govia Thameslink Railway  Grand Central  \
Time period                                                    
As of 31 March 2018                   7143.00          157.0   
As of 31 March 2019                   7276.00          193.0   
As of 31 March 2020                   7427.00          222.0   
As of 31 March 2021                   7481.27          163.0   
As of 31 March 2022                   7413.00          164.0   

                     Great Western Railway  Greater Anglia  ...   Lumo  \
Time period                                                 ...          
As of 31 March 2018                6057.00     3075.000000  ...    NaN   
As of 31 March 2019                6343.00     3103.000000  ...    NaN   
As of 31 March 2020                6452.11     2912.621087  ...    NaN   
As of 31 March 2021                6408.23     2867.000000  ...    NaN   
As of 31 March 2022                6230.00     2798.690000  ...  100.5   

                     Merseyrail  Northern Trains  ScotRail  \
Time period                                                  
As of 31 March 2018      1185.0           5837.0   4820.00   
As of 31 March 2019      1206.0           6183.0   5168.00   
As of 31 March 2020      1168.0           6351.0   5162.12   
As of 31 March 2021      1128.5           6666.0   5211.00   
As of 31 March 2022      1148.5           6854.0   4925.50   

                     South Western Railway  Southeastern  TfW Rail  \
Time period                                                          
As of 31 March 2018                5059.00       4325.00   2193.00   
As of 31 March 2019                5177.00       4410.00   2293.00   
As of 31 March 2020                5307.84       4511.00   2495.45   
As of 31 March 2021                5643.00       4480.00   2585.00   
As of 31 March 2022                5265.06       4555.72   2769.00   

                     TransPennine Express  West Midlands Trains  \
Time period                                                       
As of 31 March 2018                1117.0               2589.00   
As of 31 March 2019                1258.0               2834.00   
As of 31 March 2020                1459.0               2914.51   
As of 31 March 2021                1427.5               2886.00   
As of 31 March 2022                1569.5               2900.59   

                     Elizabeth line  
Time period                          
As of 31 March 2018     1046.000000  
As of 31 March 2019     1389.000000  
As of 31 March 2020     1515.278571  
As of 31 March 2021     1425.200000  
As of 31 March 2022     1255.371429  

[5 rows x 24 columns]

In [ ]:
full_time_employees.shape

(6, 24)

In [ ]:
full_time_employees.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, As of 31 March 2018 to As of 31 March 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              4 non-null      float64
 11  Hull Trains                   5 non-null      float64
 12  London North Eastern Railway  6 non-n

In [ ]:
full_time_employees.describe()

Avanti West Coast         c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000    6.000000            6.000000           6.000000   
mean         3431.659500  655.853333          184.333333         858.916667   
std           180.451192   23.948470           11.673331          19.764657   
min          3278.647000  633.400000          168.000000         840.000000   
25%          3304.250000  640.120000          176.500000         850.000000   
50%          3354.655000  645.230000          185.500000         851.000000   
75%          3531.577500  673.440000          193.000000         862.500000   
max          3724.000000  690.000000          198.000000         895.500000   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean    1918.600000            2410.058333               7330.796667   
std       47.508315              76.298086                129.900227   
min     1854.000000            2294.000000               7143.000000   
25%     1892.150000            2366.435000               7252.382500   
50%     1914.300000            2425.120000               7344.500000   
75%     1949.500000            2455.125000               7423.500000   
max     1983.000000            2504.110000               7481.270000   

       Grand Central  Great Western Railway  Greater Anglia  ...        Lumo  \
count       6.000000               6.000000        6.000000  ...    2.000000   
mean      178.000000            6279.223333     2924.718515  ...  102.350000   
std        24.915858             149.187242      135.162109  ...    2.616295   
min       157.000000            6057.000000     2792.000000  ...  100.500000   
25%       163.250000            6196.250000     2815.767500  ...  101.425000   
50%       166.500000            6286.500000     2889.810544  ...  102.350000   
75%       187.000000            6391.922500     3034.405272  ...  103.275000   
max       222.000000            6452.110000     3103.000000  ...  104.200000   

        Merseyrail  Northern Trains     ScotRail  South Western Railway  \
count     6.000000         6.000000     6.000000               6.000000   
mean   1176.833333      6467.183333  5042.436667            5278.188333   
std      35.928633       419.164838   159.497285             198.059410   
min    1128.500000      5837.000000  4820.000000            5059.000000   
25%    1153.375000      6225.000000  4936.125000            5187.057500   
50%    1176.500000      6508.500000  5065.060000            5241.145000   
75%    1200.750000      6807.000000  5166.530000            5297.145000   
max    1225.000000      6912.100000  5211.000000            5643.000000   

       Southeastern     TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000     6.000000              6.000000                6.0000   
mean    4460.453333  2554.808333           1405.500000             2845.3500   
std       81.643230   297.363260            186.463401              131.0482   
min     4325.000000  2193.000000           1117.000000             2589.0000   
25%     4427.500000  2343.612500           1300.375000             2847.0000   
50%     4480.500000  2540.225000           1443.250000             2893.2950   
75%     4503.500000  2723.000000           1541.875000             2911.0300   
max     4555.720000  2993.400000           1602.000000             2948.0000   

       Elizabeth line  
count        6.000000  
mean      1317.994048  
std        164.334813  
min       1046.000000  
25%       1260.807143  
50%       1333.057143  
75%       1416.150000  
max       1515.278571  

[8 rows x 24 columns]

Who has the most FTE employees?

In [ ]:
full_time_employees[full_time_employees.isin([full_time_employees.max().max()])].stack()

Time period                                  
As of 31 March 2021  Govia Thameslink Railway    7481.27
dtype: float64

At 31 March 2021, Govia Thameslink Railway had the most Full-time equivalent employees in the last five years, with 7481.27.

In [ ]:
for column in full_time_employees.columns:
  print(f"{column}: {full_time_employees[column].min()} - {full_time_employees[column].idxmin()}")


Avanti West Coast: 3278.647 - As of 31 March 2022
c2c: 633.4 - As of 31 March 2022
Caledonian Sleeper: 168.0 - As of 31 March 2018
Chiltern Railways: 840.0 - As of 31 March 2018
CrossCountry: 1854.0 - As of 31 March 2023
East Midlands Railway: 2294.0 - As of 31 March 2022
Govia Thameslink Railway: 7143.0 - As of 31 March 2018
Grand Central: 157.0 - As of 31 March 2018
Great Western Railway: 6057.0 - As of 31 March 2018
Greater Anglia: 2792.0 - As of 31 March 2023
Heathrow Express: 142.0 - As of 31 March 2023
Hull Trains: 98.0 - As of 31 March 2021
London North Eastern Railway: 3005.0 - As of 31 March 2021
London Overground: 1440.0 - As of 31 March 2018
Lumo: 100.5 - As of 31 March 2022
Merseyrail: 1128.5 - As of 31 March 2021
Northern Trains: 5837.0 - As of 31 March 2018
ScotRail: 4820.0 - As of 31 March 2018
South Western Railway: 5059.0 - As of 31 March 2018
Southeastern: 4325.0 - As of 31 March 2018
TfW Rail: 2193.0 - As of 31 March 2018
TransPennine Express: 1117.0 - As of 31 March

In [ ]:
full_time_employees[full_time_employees.isin([full_time_employees.min().min()])].stack()

Time period                     
As of 31 March 2021  Hull Trains    98.0
dtype: float64

At 31 March 2021, Hull Trains had the least Full-time equivalent employees in the last five years, with 98.0.

In [ ]:
total_full_time_employees = full_time_employees.sum(axis=1)

In [ ]:
total_full_time_employees[total_full_time_employees.isin([total_full_time_employees.max().max()])]

Time period
As of 31 March 2021    62644.57
dtype: float64

Industry wide, the number of FTE equivalent employees peaked at 31 March 2021, with 62644.57

In [ ]:
total_full_time_employees[total_full_time_employees.isin([total_full_time_employees.min().min()])]

Time period
As of 31 March 2018    59007.0
dtype: float64

Industry wide, the number of FTE equivalent employees peaked at 31 March 2018, with 59007


## Managed Stations

In [ ]:
managed_stations = data_tables["Number of stations managed"]
managed_stations.head()

Avanti West Coast   c2c  Caledonian Sleeper  \
Time period                                                        
As of 31 March 2018               17.0  25.0                 0.0   
As of 31 March 2019               16.0  25.0                 NaN   
As of 31 March 2020               16.0  25.0                 NaN   
As of 31 March 2021               16.0  25.0                 NaN   
As of 31 March 2022               16.0  25.0                 NaN   

                     Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                   
As of 31 March 2018               35.0           0.0                   90.0   
As of 31 March 2019               35.0           NaN                   90.0   
As of 31 March 2020               35.0           NaN                   90.0   
As of 31 March 2021               35.0           NaN                   90.0   
As of 31 March 2022               35.0           NaN                  102.0   

                     Govia Thameslink Railway  Grand Central  \
Time period                                                    
As of 31 March 2018                     236.0            0.0   
As of 31 March 2019                     235.0            NaN   
As of 31 March 2020                     235.0            NaN   
As of 31 March 2021                     235.0            NaN   
As of 31 March 2022                     235.0            NaN   

                     Great Western Railway  Greater Anglia  ...  Lumo  \
Time period                                                 ...         
As of 31 March 2018                  196.0           133.0  ...   NaN   
As of 31 March 2019                  196.0           133.0  ...   NaN   
As of 31 March 2020                  197.0           133.0  ...   NaN   
As of 31 March 2021                  194.0           133.0  ...   NaN   
As of 31 March 2022                  194.0           134.0  ...   NaN   

                     Merseyrail  Northern Trains  ScotRail  \
Time period                                                  
As of 31 March 2018        66.0            476.0     356.0   
As of 31 March 2019        66.0            478.0     354.0   
As of 31 March 2020        66.0            476.0     354.0   
As of 31 March 2021        66.0            477.0     355.0   
As of 31 March 2022        66.0            465.0     355.0   

                     South Western Railway  Southeastern  TfW Rail  \
Time period                                                          
As of 31 March 2018                  186.0         164.0     247.0   
As of 31 March 2019                  184.0         164.0     247.0   
As of 31 March 2020                  184.0         164.0     247.0   
As of 31 March 2021                  187.0         164.0     248.0   
As of 31 March 2022                  187.0         164.0     248.0   

                     TransPennine Express  West Midlands Trains  \
Time period                                                       
As of 31 March 2018                  19.0                 148.0   
As of 31 March 2019                  19.0                 149.0   
As of 31 March 2020                  19.0                 149.0   
As of 31 March 2021                  19.0                 149.0   
As of 31 March 2022                  19.0                 149.0   

                     Elizabeth line  
Time period                          
As of 31 March 2018            24.0  
As of 31 March 2019            24.0  
As of 31 March 2020            24.0  
As of 31 March 2021            24.0  
As of 31 March 2022            24.0  

[5 rows x 24 columns]

In [ ]:
managed_stations.shape

(6, 24)

In [ ]:
managed_stations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, As of 31 March 2018 to As of 31 March 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            1 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  1 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 1 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              4 non-null      float64
 11  Hull Trains                   1 non-null      float64
 12  London North Eastern Railway  6 non-n

In [ ]:
managed_stations.describe()

Avanti West Coast   c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000   6.0                 1.0                6.0   
mean           16.166667  25.0                 0.0               35.0   
std             0.408248   0.0                 NaN                0.0   
min            16.000000  25.0                 0.0               35.0   
25%            16.000000  25.0                 0.0               35.0   
50%            16.000000  25.0                 0.0               35.0   
75%            16.000000  25.0                 0.0               35.0   
max            17.000000  25.0                 0.0               35.0   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count           1.0               6.000000                  6.000000   
mean            0.0              94.000000                235.166667   
std             NaN               6.196773                  0.408248   
min             0.0              90.000000                235.000000   
25%             0.0              90.000000                235.000000   
50%             0.0              90.000000                235.000000   
75%             0.0              99.000000                235.000000   
max             0.0             102.000000                236.000000   

       Grand Central  Great Western Railway  Greater Anglia  ...  Lumo  \
count            1.0               6.000000        6.000000  ...   0.0   
mean             0.0             195.166667      133.333333  ...   NaN   
std              NaN               1.329160        0.516398  ...   NaN   
min              0.0             194.000000      133.000000  ...   NaN   
25%              0.0             194.000000      133.000000  ...   NaN   
50%              0.0             195.000000      133.000000  ...   NaN   
75%              0.0             196.000000      133.750000  ...   NaN   
max              0.0             197.000000      134.000000  ...   NaN   

       Merseyrail  Northern Trains    ScotRail  South Western Railway  \
count         6.0         6.000000    6.000000               6.000000   
mean         66.0       472.833333  355.166667             185.833333   
std           0.0         6.112828    1.169045               1.471960   
min          66.0       465.000000  354.000000             184.000000   
25%          66.0       467.750000  354.250000             184.500000   
50%          66.0       476.000000  355.000000             186.500000   
75%          66.0       476.750000  355.750000             187.000000   
max          66.0       478.000000  357.000000             187.000000   

       Southeastern    TfW Rail  TransPennine Express  West Midlands Trains  \
count           6.0    6.000000                   6.0              6.000000   
mean          164.0  247.500000                  19.0            148.833333   
std             0.0    0.547723                   0.0              0.408248   
min           164.0  247.000000                  19.0            148.000000   
25%           164.0  247.000000                  19.0            149.000000   
50%           164.0  247.500000                  19.0            149.000000   
75%           164.0  248.000000                  19.0            149.000000   
max           164.0  248.000000                  19.0            149.000000   

       Elizabeth line  
count        6.000000  
mean        24.833333  
std          2.041241  
min         24.000000  
25%         24.000000  
50%         24.000000  
75%         24.000000  
max         29.000000  

[8 rows x 24 columns]

In [ ]:
managed_stations[managed_stations.isin([managed_stations.max().max()])].stack()

Time period                         
As of 31 March 2019  Northern Trains    478.0
dtype: float64

Northern Trains managed the most stations at 31 March 2019, with 478 stations

In [ ]:
managed_stations[managed_stations.isin([managed_stations.min().min()])].stack()

Time period                            
As of 31 March 2018  Caledonian Sleeper    0.0
                     CrossCountry          0.0
                     Grand Central         0.0
                     Hull Trains           0.0
dtype: float64

Multiple operators do not manage any stations.

In [ ]:
total_managed_stations = managed_stations.sum(axis=1)

In [ ]:
total_managed_stations[total_managed_stations.isin([total_managed_stations.max().max()])]

Time period
As of 31 March 2023    2521.0
dtype: float64

In [ ]:
total_managed_stations[total_managed_stations.isin([total_managed_stations.min().min()])]

Time period
As of 31 March 2019    2507.0
dtype: float64

The lowest number of total stations managed was in 2019 with 2507, and the largest number of total stations managed was in 2022 with 2513.

## Employees per station

How many FTE employees on average per station?

In [ ]:
employees_per_station = full_time_employees/managed_stations

In [ ]:
employees_per_station[employees_per_station.isin([-np.inf, np.inf])].stack()

Time period                            
As of 31 March 2018  Caledonian Sleeper    inf
                     CrossCountry          inf
                     Grand Central         inf
dtype: float64

Some will have FTE employees to managed stations ratio of infinity, and this is because the TOC has no stations to manage

In [ ]:
employees_per_station = employees_per_station.replace(to_replace=np.inf, value=np.nan, regex=True)

In [ ]:
employees_per_station[employees_per_station.isin([employees_per_station.min().min()])].stack()

Time period                  
As of 31 March 2018  TfW Rail    8.878543
dtype: float64

In [ ]:
employees_per_station[employees_per_station.isin([employees_per_station.max().max()])].stack()

Time period                                      
As of 31 March 2018  London North Eastern Railway    314.181818
dtype: float64

TfW has the lowest FTE employees to managed stations ratio out of the TOCs as of 31 March 2018. London North Eastern Railway had the highest, also as of 31 March 2018.

## Passenger journeys (millions)

In [ ]:
journeys = data_tables["Passenger journeys (millions)"]
journeys.head()

Avanti West Coast        c2c  Caledonian Sleeper  \
Time period                                                              
Apr 2017 to Mar 2018          38.285101  47.873649            0.298675   
Apr 2018 to Mar 2019          39.476464  49.142540            0.305180   
Apr 2019 to Mar 2020          37.475104  47.323080            0.314897   
Apr 2020 to Mar 2021           6.159637  15.012377            0.078290   
Apr 2021 to Mar 2022          21.556892  28.061517            0.221836   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018          28.104042     40.140707              27.186188   
Apr 2018 to Mar 2019          29.322577     40.631927              26.733801   
Apr 2019 to Mar 2020          28.390970     39.775797              25.388451   
Apr 2020 to Mar 2021           4.619612      6.737393               5.066245   
Apr 2021 to Mar 2022          14.274311     20.619891              17.997429   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018                318.837055       1.389025   
Apr 2018 to Mar 2019                341.491261       1.505269   
Apr 2019 to Mar 2020                348.854219       1.407642   
Apr 2020 to Mar 2021                 76.104215       0.166402   
Apr 2021 to Mar 2022                179.000656       1.027238   

                      Great Western Railway  Greater Anglia  ...      Lumo  \
Time period                                                  ...             
Apr 2017 to Mar 2018             103.673747       81.337350  ...       NaN   
Apr 2018 to Mar 2019             100.043995       84.945308  ...       NaN   
Apr 2019 to Mar 2020              97.039313       84.946751  ...       NaN   
Apr 2020 to Mar 2021              17.937480       19.000892  ...       NaN   
Apr 2021 to Mar 2022              55.142334       49.584467  ...  0.319159   

                      Merseyrail  Northern Trains   ScotRail  \
Time period                                                    
Apr 2017 to Mar 2018   30.645443       103.321681  97.775300   
Apr 2018 to Mar 2019   30.802342       101.338180  97.777786   
Apr 2019 to Mar 2020   30.636451       107.990663  96.424648   
Apr 2020 to Mar 2021    9.024525        21.913866  14.384873   
Apr 2021 to Mar 2022   21.040209        67.492846  46.694824   

                      South Western Railway  Southeastern   TfW Rail  \
Time period                                                            
Apr 2017 to Mar 2018             211.815355    176.243109  32.935510   
Apr 2018 to Mar 2019             215.979112    183.248933  33.450558   
Apr 2019 to Mar 2020             203.659760    179.493156  31.835413   
Apr 2020 to Mar 2021              45.680090     40.165038   5.021376   
Apr 2021 to Mar 2022             108.541098     97.783252  17.647574   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018             27.850815             74.929911   
Apr 2018 to Mar 2019             29.246730             78.687460   
Apr 2019 to Mar 2020             28.587891             79.542782   
Apr 2020 to Mar 2021              5.396005             13.617949   
Apr 2021 to Mar 2022             16.161344             42.385009   

                      Elizabeth line  
Time period                           
Apr 2017 to Mar 2018       42.378601  
Apr 2018 to Mar 2019       51.292324  
Apr 2019 to Mar 2020       55.506996  
Apr 2020 to Mar 2021       18.027844  
Apr 2021 to Mar 2022       37.371677  

[5 rows x 24 columns]

In [ ]:
journeys.shape

(6, 24)

In [ ]:
journeys.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
journeys.describe()

Avanti West Coast        c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000   6.000000            6.000000           6.000000   
mean           28.256457  36.864690            0.247383          20.674699   
std            13.018381  13.754174            0.089554           9.899928   
min             6.159637  15.012377            0.078290           4.619612   
25%            22.814056  29.489881            0.232732          15.539903   
50%            32.030325  40.549028            0.282046          23.720361   
75%            38.082601  47.736007            0.303554          28.319238   
max            39.476464  49.142540            0.314897          29.322577   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean      29.278746              21.319896                252.443243   
std       13.729089               8.641382                107.820518   
min        6.737393               5.066245                 76.104215   
25%       22.406609              19.845184                196.843506   
50%       33.771280              25.467856                284.604555   
75%       40.049479              26.437166                335.827709   
max       40.631927              27.186188                348.854219   

       Grand Central  Great Western Railway  Greater Anglia  ...      Lumo  \
count       6.000000               6.000000        6.000000  ...  2.000000   
mean        1.181568              75.169873       64.409488  ...  0.732545   
std         0.533531              33.436999       26.140996  ...  0.584617   
min         0.166402              17.937480       19.000892  ...  0.319159   
25%         1.117684              60.652343       53.848890  ...  0.525852   
50%         1.398333              87.110842       73.989754  ...  0.732545   
75%         1.480862              99.292824       84.043318  ...  0.939238   
max         1.593835             103.673747       84.946751  ...  1.145931   

       Merseyrail  Northern Trains   ScotRail  South Western Railway  \
count    6.000000         6.000000   6.000000               6.000000   
mean    24.608037        80.570021  69.457218             154.006297   
std      8.573575        32.597643  34.396537              68.839476   
min      9.024525        21.913866  14.384873              45.680090   
25%     22.154969        70.960358  50.942587             115.996414   
50%     28.067850        91.350536  80.055262             171.011062   
75%     30.643195       102.825806  97.437637             209.776456   
max     30.802342       107.990663  97.777786             215.979112   

       Southeastern   TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000   6.000000              6.000000              6.000000   
mean     132.408420  24.008091             21.080938             57.566070   
std       57.710844  11.240996              9.407060             26.054827   
min       40.165038   5.021376              5.396005             13.617949   
25%      102.716697  19.025209             16.931719             45.847084   
50%      146.880069  27.496764             23.546830             65.581609   
75%      178.680644  32.660485             28.403622             77.748073   
max      183.248933  33.450558             29.246730             79.542782   

       Elizabeth line  
count        6.000000  
mean        68.145517  
std         67.975538  
min         18.027844  
25%         38.623408  
50%         46.835462  
75%         54.453328  
max        204.295662  

[8 rows x 24 columns]

In [ ]:
journeys[journeys.isin([journeys.max().max()])].stack()

Time period                                   
Apr 2019 to Mar 2020  Govia Thameslink Railway    348.854219
dtype: float64

In [ ]:
journeys[journeys.isin([journeys.min().min()])].stack()

Time period                      
Apr 2020 to Mar 2021  Hull Trains    0.0773
dtype: float64

Govia Thameslink had the greatest number of annual journeys in Apr 2019 - Mar 2020 with 348.8 million journeys.

Hull Trains had the lowest in Apr 2020 - Mar 2021  with 0.077 million journeys

In [ ]:
total_journeys = journeys.sum(axis=1)

In [ ]:
total_journeys[total_journeys.isin([total_journeys.max().max()])]

Time period
Apr 2018 to Mar 2019    1752.982619
dtype: float64

In [ ]:
total_journeys[total_journeys.isin([total_journeys.min().min()])]

Time period
Apr 2020 to Mar 2021    387.885467
dtype: float64

Total journeys throughout the country was at its greatest between Apr 2018 and Mar 2019 with 1753 million journeys.

At its lowest, only 387.9 million journeys were achieved, between Apr 2020 and Mar 2021

## Route kilometers operated

In [ ]:
route_km = data_tables["Route kilometres operated"]

In [ ]:
route_km.shape

(6, 24)

In [ ]:
route_km.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, As of 31 March 2018 to As of 31 March 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              4 non-null      float64
 11  Hull Trains                   5 non-null      float64
 12  London North Eastern Railway  6 non-n

In [ ]:
route_km.describe()

Avanti West Coast         c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000    6.000000            6.000000           6.000000   
mean         1302.493739  125.528693         1470.926944         352.168896   
std            18.395352    0.000340            0.020871           5.237653   
min          1264.944384  125.528000         1470.900000         349.200000   
25%          1310.000000  125.528830         1470.910104         349.206912   
50%          1310.003008  125.528832         1470.940416         349.227648   
75%          1310.006016  125.528832         1470.940416         352.848672   
max          1310.006016  125.528832         1470.940416         362.102400   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean    2710.123531            1531.835515               1272.165408   
std        0.018227              28.053064                 20.808534   
min     2710.100000            1490.300000               1234.366848   
25%     2710.108824            1513.589568               1268.050000   
50%     2710.135296            1549.798272               1277.837600   
75%     2710.135296            1549.798272               1287.475200   
max     2710.135296            1549.798272               1287.475200   

       Grand Central  Great Western Railway  Greater Anglia  ...    Lumo  \
count           6.00               6.000000        6.000000  ...    2.00   
mean          518.46            1997.197269      510.699589  ...  629.55   
std             0.00               0.002115        0.416380  ...    0.00   
min           518.46            1997.195904      510.162048  ...  629.55   
25%           518.46            1997.195904      510.363216  ...  629.55   
50%           518.46            1997.195904      510.966720  ...  629.55   
75%           518.46            1997.198976      510.969180  ...  629.55   
max           518.46            1997.200000      510.970000  ...  629.55   

       Merseyrail  Northern Trains     ScotRail  South Western Railway  \
count    6.000000         6.000000     6.000000               6.000000   
mean   120.700742      3051.208328  3120.512011             997.896323   
std      0.000405       195.103647     0.009303               0.169085   
min    120.700000      2800.258560  3120.500000             997.793280   
25%    120.700800      2889.693920  3120.504504             997.793280   
50%    120.700800      3158.000000  3120.518016             997.796640   
75%    120.700800      3185.024637  3120.518016             997.950000   
max    120.701250      3196.700000  3120.518016             998.198097   

       Southeastern     TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000     6.000000              6.000000              6.000000   
mean     748.329973  1785.900245           1200.286677            899.615531   
std        0.023217    81.151909            108.230004              0.012030   
min      748.300000  1623.828096           1039.636224            899.600000   
25%      748.311240  1795.221872           1131.570000            899.605824   
50%      748.344960  1826.602720           1252.874304            899.623296   
75%      748.344960  1826.605440           1252.893576            899.623296   
max      748.344960  1827.000000           1312.300000            899.623296   

       Elizabeth line  
count        6.000000  
mean        88.771898  
std         24.128327  
min         58.741056  
25%         69.354680  
50%         98.781535  
75%         98.781535  
max        118.000000  

[8 rows x 24 columns]

In [ ]:
route_km[route_km.isin([route_km.max().max()])].stack()

Time period                         
As of 31 March 2021  Northern Trains    3196.7
dtype: float64

In [ ]:
route_km[route_km.isin([route_km.min().min()])].stack()

Time period                          
As of 31 March 2023  Heathrow Express    28.968
dtype: float64

In the last five years, Northern Trains operated the most amount of route, at 3197 km of route under their operation at 31 March 2021.

Heathrow Express operates the least amount of track, at 29 km for their entire route.

In [ ]:
total_route_km = route_km.sum(axis=1)

In [ ]:
total_route_km[total_route_km.isin([total_route_km.max().max()])]

Time period
As of 31 March 2023    26739.947696
dtype: float64

In [ ]:
total_route_km[total_route_km.isin([total_route_km.min().min()])]

Time period
As of 31 March 2018    24853.14389
dtype: float64

Country-wide, routes under operation has increased over time, from 24,853 km to 26,673 km of route operated

## Who are the biggest and smallest TOC's?

### The biggest and smallest today

There are a number of possible ways to define the "Biggest" TOC's.


*   Full-time equivalent (FTE) employees
*   Managed Stations
*   Passenger journeys
*   Route kilometers operated

In [ ]:
top_fte = full_time_employees.transpose().sort_values(by="As of 31 March 2023", ascending=False)["As of 31 March 2023"].head()
top_fte

Govia Thameslink Railway    7244.51
Northern Trains             6912.10
Great Western Railway       6185.00
South Western Railway       5217.23
ScotRail                    4968.00
Name: As of 31 March 2023, dtype: float64

In [ ]:
top_managed_stations = managed_stations.transpose().sort_values(by="As of 31 March 2023", ascending=False)["As of 31 March 2023"].head()
top_managed_stations

Northern Trains             465.0
ScotRail                    357.0
TfW Rail                    248.0
Govia Thameslink Railway    235.0
Great Western Railway       194.0
Name: As of 31 March 2023, dtype: float64

In [ ]:
top_journeys = journeys.transpose().sort_values(by="Apr 2021 to Mar 2022", ascending=False)["Apr 2021 to Mar 2022"].head()
top_journeys

Govia Thameslink Railway    179.000656
London Overground           126.888455
South Western Railway       108.541098
Southeastern                 97.783252
Northern Trains              67.492846
Name: Apr 2021 to Mar 2022, dtype: float64

In [ ]:
top_route_km = route_km.transpose().sort_values(by="As of 31 March 2023", ascending=False)["As of 31 March 2023"].head()
top_route_km

Northern Trains          3158.0
ScotRail                 3120.5
CrossCountry             2710.1
Great Western Railway    1997.2
TfW Rail                 1826.6
Name: As of 31 March 2023, dtype: float64

Northern Trains are in the top 5 for all four of the above metrics. Govia Thameslink Railway, ScotRail and Great Western Railway appear in the top 5 in three of the four metrics. These four TOC's can therefore be considered the biggest TOC's.

In [ ]:
bottom_fte = full_time_employees.transpose().sort_values(by="As of 31 March 2023", ascending=True)["As of 31 March 2023"].head()
bottom_fte

Hull Trains           100.0
Lumo                  104.2
Heathrow Express      142.0
Grand Central         169.0
Caledonian Sleeper    198.0
Name: As of 31 March 2023, dtype: float64

In [ ]:
bottom_managed_stations = managed_stations.transpose().sort_values(by="As of 31 March 2023", ascending=True, na_position="first")["As of 31 March 2023"].head()
bottom_managed_stations

Caledonian Sleeper   NaN
CrossCountry         NaN
Grand Central        NaN
Hull Trains          NaN
Lumo                 NaN
Name: As of 31 March 2023, dtype: float64

In [ ]:
bottom_journeys = journeys.transpose().sort_values(by="Apr 2021 to Mar 2022", ascending=True)["Apr 2021 to Mar 2022"].head()
bottom_journeys

Caledonian Sleeper    0.221836
Lumo                  0.319159
Hull Trains           0.761796
Grand Central         1.027238
Heathrow Express      1.783396
Name: Apr 2021 to Mar 2022, dtype: float64

In [ ]:
bottom_route_km = route_km.transpose().sort_values(by="As of 31 March 2023", ascending=True)["As of 31 March 2023"].head()
bottom_route_km

Heathrow Express      28.96800
Elizabeth line       118.00000
Merseyrail           120.70125
c2c                  125.52883
London Overground    169.87000
Name: As of 31 March 2023, dtype: float64

Hull Trains, Lumo, Heathrow Express, Grand Central, Caledonian Sleeper are TOCs that make it in the bottom 5 in three of the four metrics, and can therefore be considered the smallest TOC's.

### The biggest and smallest before COVID-19

Could Northern Trains, Govia Thameslink Railway, and Great Western Railway be considered as the biggest TOCs before COVID?

In [ ]:
top_fte_2019 = full_time_employees.transpose().sort_values(by="As of 31 March 2019", ascending=False)["As of 31 March 2019"].head()
top_fte_2019

Govia Thameslink Railway    7276.0
Great Western Railway       6343.0
Northern Trains             6183.0
South Western Railway       5177.0
ScotRail                    5168.0
Name: As of 31 March 2019, dtype: float64

In [ ]:
top_managed_stations_2019 = managed_stations.transpose().sort_values(by="As of 31 March 2019", ascending=False)["As of 31 March 2019"].head()
top_managed_stations_2019

Northern Trains             478.0
ScotRail                    354.0
TfW Rail                    247.0
Govia Thameslink Railway    235.0
Great Western Railway       196.0
Name: As of 31 March 2019, dtype: float64

In [ ]:
top_journeys_2019 = journeys.transpose().sort_values(by="Apr 2019 to Mar 2020", ascending=False)["Apr 2019 to Mar 2020"].head()
top_journeys_2019

Govia Thameslink Railway    348.854219
South Western Railway       203.659760
London Overground           186.044201
Southeastern                179.493156
Northern Trains             107.990663
Name: Apr 2019 to Mar 2020, dtype: float64

In [ ]:
top_route_km_2019 = route_km.transpose().sort_values(by="As of 31 March 2019", ascending=False)["As of 31 March 2019"].head()
top_route_km_2019

ScotRail                 3120.518016
Northern Trains          2800.258560
CrossCountry             2710.135296
Great Western Railway    1997.195904
TfW Rail                 1784.762496
Name: As of 31 March 2019, dtype: float64

Northern Trains is in the top 5 for all four metrics. Govia Thameslink Railway, ScotRail and Great Western Railway appear in the top 5 for three metrics. These TOC's can be considered the biggest TOC's before and after COVID-19.

In [ ]:
bottom_fte_2019 = full_time_employees.transpose().sort_values(by="As of 31 March 2019", ascending=True)["As of 31 March 2019"].head()
bottom_fte_2019

Hull Trains           119.0
Caledonian Sleeper    174.0
Grand Central         193.0
c2c                   690.0
Chiltern Railways     852.0
Name: As of 31 March 2019, dtype: float64

In [ ]:
bottom_managed_stations_2019 = managed_stations.transpose().sort_values(by="As of 31 March 2019", ascending=True, na_position="first")["As of 31 March 2019"].head()
bottom_managed_stations_2019

Caledonian Sleeper   NaN
CrossCountry         NaN
Grand Central        NaN
Heathrow Express     NaN
Hull Trains          NaN
Name: As of 31 March 2019, dtype: float64

In [ ]:
bottom_journeys_2019 = journeys.transpose().sort_values(by="Apr 2019 to Mar 2020", ascending=True)["Apr 2019 to Mar 2020"].head()
bottom_journeys_2019

Caledonian Sleeper               0.314897
Hull Trains                      1.045790
Grand Central                    1.407642
Heathrow Express                 5.822825
London North Eastern Railway    21.232981
Name: Apr 2019 to Mar 2020, dtype: float64

In [ ]:
bottom_route_km_2019 = route_km.transpose().sort_values(by="As of 31 March 2019", ascending=True)["As of 31 March 2019"].head()
bottom_route_km_2019

Elizabeth line        59.545728
Merseyrail           120.700800
c2c                  125.528832
London Overground    167.371776
Hull Trains          344.399616
Name: As of 31 March 2019, dtype: float64

Lumo, who did not exist in 2019, as well as Heathrow Express, who had incomplete data for 2019 were ignored. Hull Trains were in the bottom 5 in all four metrics. Caledonian Sleeper and Grand Central were in the bottom 5 in three metrics. Hull Trains, Caledonian Sleeper and Grand Central could be considered the smallest TOC's before and after COVID-19. There is not enough data to confirm that Heathrow Express would be a part of this group.

## Passenger kilometres (millions)

Passenger kilometres refer to the distance travelled by passengers.

In [ ]:
passenger_km = data_tables["Passenger kilometres (millions)"]
passenger_km

Avanti West Coast          c2c  Caledonian Sleeper  \
Time period                                                                
Apr 2017 to Mar 2018        7582.332601  1211.872484          194.647870   
Apr 2018 to Mar 2019        7673.167045  1237.823744          200.976440   
Apr 2019 to Mar 2020        7388.251686  1201.033954          206.017459   
Apr 2020 to Mar 2021        1155.280890   329.440545           58.147238   
Apr 2021 to Mar 2022        4225.480142   621.998402          149.958398   
Apr 2022 to Mar 2023        5095.891109   774.532563          175.020957   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018        1598.462173   3761.984367            2451.637531   
Apr 2018 to Mar 2019        1652.390713   3714.418952            2415.032302   
Apr 2019 to Mar 2020        1579.479666   3638.553963            2249.543953   
Apr 2020 to Mar 2021         213.957799    560.475729             410.151645   
Apr 2021 to Mar 2022         750.552990   1814.298180            1488.525169   
Apr 2022 to Mar 2023        1051.281495   2427.641835            2197.386593   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018               8749.573801     388.557376   
Apr 2018 to Mar 2019               9206.798734     418.447881   
Apr 2019 to Mar 2020               9342.625204     388.951648   
Apr 2020 to Mar 2021               1776.838603      43.099591   
Apr 2021 to Mar 2022               4695.474204     282.959741   
Apr 2022 to Mar 2023               6838.901365     430.045475   

                      Great Western Railway  Greater Anglia  ...        Lumo  \
Time period                                                  ...               
Apr 2017 to Mar 2018            5991.555182     3802.129752  ...         NaN   
Apr 2018 to Mar 2019            6000.710674     3925.175882  ...         NaN   
Apr 2019 to Mar 2020            5965.160993     3868.418225  ...         NaN   
Apr 2020 to Mar 2021            1105.895154      756.902238  ...         NaN   
Apr 2021 to Mar 2022            3804.458473     2102.212028  ...  151.574879   
Apr 2022 to Mar 2023            5370.241630     2878.656878  ...  537.418871   

                      Merseyrail  Northern Trains     ScotRail  \
Time period                                                      
Apr 2017 to Mar 2018  551.668123      2586.042038  2959.026893   
Apr 2018 to Mar 2019  548.789553      2584.595083  2978.778087   
Apr 2019 to Mar 2020  556.348769      2893.035887  2908.919925   
Apr 2020 to Mar 2021  165.087950       591.387433   396.653010   
Apr 2021 to Mar 2022  382.478477      2000.636047  1473.497719   
Apr 2022 to Mar 2023  451.489594      2473.332516  2051.743121   

                      South Western Railway  Southeastern     TfW Rail  \
Time period                                                              
Apr 2017 to Mar 2018            5937.833456   4548.860711  1247.288555   
Apr 2018 to Mar 2019            6039.589156   4693.138188  1242.679864   
Apr 2019 to Mar 2020            5705.806930   4629.103487  1170.208983   
Apr 2020 to Mar 2021            1110.947423    995.090288   186.600428   
Apr 2021 to Mar 2022            3058.444605   2542.582733   734.743821   
Apr 2022 to Mar 2023            4015.917858   3145.092897   977.299732   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018           2010.219755           2803.113653   
Apr 2018 to Mar 2019           2081.735919           2919.370953   
Apr 2019 to Mar 2020           2058.461437           3147.624666   
Apr 2020 to Mar 2021            398.124303            536.269890   
Apr 2021 to Mar 2022           1186.126779           1712.270401   
Apr 2022 to 

In [ ]:
passenger_km.shape

(6, 24)

In [ ]:
passenger_km.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
passenger_km.describe()

Avanti West Coast          c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000     6.000000            6.000000           6.000000   
mean         5520.067246   896.116949          164.128060        1141.020806   
std          2580.160124   379.601201           55.848640         580.165844   
min          1155.280890   329.440545           58.147238         213.957799   
25%          4443.082884   660.131942          156.224038         825.735116   
50%          6242.071398   987.783259          184.834414        1315.380580   
75%          7533.812373  1209.162852          199.394297        1593.716546   
max          7673.167045  1237.823744          206.017459        1652.390713   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean    2652.895504            1868.712865               6768.368652   
std     1300.818045             795.395291               3023.744380   
min      560.475729             410.151645               1776.838603   
25%     1967.634094            1665.740525               5231.330994   
50%     3033.097899            2223.465273               7794.237583   
75%     3695.452704            2373.660215               9092.492501   
max     3761.984367            2451.637531               9342.625204   

       Grand Central  Great Western Railway  Greater Anglia  ...        Lumo  \
count       6.000000               6.000000        6.000000  ...    2.000000   
mean      325.343619            4706.337018     2888.915834  ...  344.496875   
std       147.736879            1955.973545     1267.415447  ...  272.832903   
min        43.099591            1105.895154      756.902238  ...  151.574879   
25%       309.359150            4195.904262     2296.323241  ...  248.035877   
50%       388.754512            5667.701312     3340.393315  ...  344.496875   
75%       411.073823            5984.956635     3851.846107  ...  440.957873   
max       430.045475            6000.710674     3925.175882  ...  537.418871   

       Merseyrail  Northern Trains     ScotRail  South Western Railway  \
count    6.000000         6.000000     6.000000               6.000000   
mean   442.643744      2188.171501  2128.103126            4311.423238   
std    152.851174       834.085383  1044.606688            1973.646262   
min    165.087950       591.387433   396.653010            1110.947423   
25%    399.731256      2118.810164  1618.059069            3297.812918   
50%    500.139573      2528.963800  2480.331523            4860.862394   
75%    550.948480      2585.680300  2946.500151            5879.826824   
max    556.348769      2893.035887  2978.778087            6039.589156   

       Southeastern     TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000     6.000000              6.000000              6.000000   
mean    3425.644717   926.470230           1522.797658           2235.760646   
std     1488.796125   412.085304            667.791740            978.431173   
min      995.090288   186.600428            398.124303            536.269890   
25%     2693.210274   795.382799           1240.124523           1858.181378   
50%     3846.976804  1073.754357           1706.168756           2549.513982   
75%     4609.042793  1224.562143           2046.401017           2890.306628   
max     4693.138188  1247.288555           2081.735919           3147.624666   

       Elizabeth line  
count        6.000000  
mean       707.803903  
std        506.787646  
min        221.594994  
25%        478.280933  
50%        588.210394  
75%        689.910199  
max       1683.359724  

[8 rows x 24 columns]

In [ ]:
passenger_km[passenger_km.isin([passenger_km.max().max()])].stack()

Time period                                   
Apr 2019 to Mar 2020  Govia Thameslink Railway    9342.625204
dtype: float64

In [ ]:
passenger_km[passenger_km.isin([passenger_km.min().min()])].stack()

Time period                           
Apr 2020 to Mar 2021  Heathrow Express    7.037339
dtype: float64

Govia Thameslink had the greatest number passenger kilometres in Apr Apr 2019 to Mar 2020 with 9.3 billion passenger kilometres.

Heathrow Express had the lowest in Apr 2020 to Mar 2021 with 77 thousand passenger kilometres

In [ ]:
total_passenger_km = passenger_km.sum(axis=1)

In [ ]:
total_passenger_km[total_passenger_km.isin([total_passenger_km.max().max()])]

Time period
Apr 2018 to Mar 2019    67668.511978
dtype: float64

In [ ]:
total_passenger_km[total_passenger_km.isin([total_passenger_km.min().min()])]

Time period
Apr 2020 to Mar 2021    12502.372796
dtype: float64

Total passenger kilometres throughout the country was at its greatest between Apr 2018 and Mar 2019 with 67.7 billion passenger kilometres.

At its lowest, only 12.5 billion passenger kilometres were achieved, between Apr 2020 and Mar 2021

## Passenger train kilometres (millions)

Passenger kilometres refer to the distance travelled by passenger trains.

In [ ]:
train_km = data_tables["Passenger train kilometres (millions)"]
train_km

Avanti West Coast       c2c  Caledonian Sleeper  \
Time period                                                             
Apr 2017 to Mar 2018          35.285905  7.294806            1.402466   
Apr 2018 to Mar 2019          35.952790  7.285512            1.420639   
Apr 2019 to Mar 2020          35.292598  7.180397            1.391045   
Apr 2020 to Mar 2021          25.565373  5.970295            0.889568   
Apr 2021 to Mar 2022          25.697847  5.994453            1.312459   
Apr 2022 to Mar 2023          23.756465  5.908183            1.385115   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018          12.268718     32.487158              22.966493   
Apr 2018 to Mar 2019          12.984113     32.675155              22.791042   
Apr 2019 to Mar 2020          12.801589     32.771591              22.420822   
Apr 2020 to Mar 2021           9.351618     19.479801              19.167262   
Apr 2021 to Mar 2022           9.859809     21.484287              22.919265   
Apr 2022 to Mar 2023           9.071378     20.610801              22.733988   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018                 61.039381       2.538946   
Apr 2018 to Mar 2019                 63.265601       2.544411   
Apr 2019 to Mar 2020                 69.065904       2.418965   
Apr 2020 to Mar 2021                 59.732563       0.779314   
Apr 2021 to Mar 2022                 57.395761       2.143358   
Apr 2022 to Mar 2023                 54.698701       2.501334   

                      Great Western Railway  Greater Anglia  ...      Lumo  \
Time period                                                  ...             
Apr 2017 to Mar 2018              43.124445       28.493350  ...       NaN   
Apr 2018 to Mar 2019              43.215161       28.505390  ...       NaN   
Apr 2019 to Mar 2020              45.189260       29.058676  ...       NaN   
Apr 2020 to Mar 2021              35.946496       24.936907  ...       NaN   
Apr 2021 to Mar 2022              42.367897       25.696167  ...  0.664873   
Apr 2022 to Mar 2023              42.538866       24.665694  ...  2.017653   

                      Merseyrail  Northern Trains   ScotRail  \
Time period                                                    
Apr 2017 to Mar 2018    6.071994        46.455680  47.362192   
Apr 2018 to Mar 2019    6.375709        48.569973  47.646847   
Apr 2019 to Mar 2020    6.490946        56.409438  49.041104   
Apr 2020 to Mar 2021    4.295194        39.793827  35.864820   
Apr 2021 to Mar 2022    5.399859        48.718240  38.591083   
Apr 2022 to Mar 2023    6.017299        44.365039  38.814640   

                      South Western Railway  Southeastern   TfW Rail  \
Time period                                                            
Apr 2017 to Mar 2018              39.046155     31.820959  23.807642   
Apr 2018 to Mar 2019              39.317375     35.825177  23.807885   
Apr 2019 to Mar 2020              38.485144     35.440493  23.861598   
Apr 2020 to Mar 2021              28.575964     29.225058  17.091445   
Apr 2021 to Mar 2022              33.024128     30.005713  20.128270   
Apr 2022 to Mar 2023              32.187384     28.972025  21.531689   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018             17.879545             25.054288   
Apr 2018 to Mar 2019             20.634906             25.618301   
Apr 2019 to Mar 2020             21.110044             27.863244   
Apr 2020 to Mar 2021             13.427686             20.435191   
Apr 2021 to Mar 2022             15.656417             22.310690   
Apr 2022 to Mar 2023             12.044987             21.418342   

               

In [ ]:
train_km.shape

(6, 24)

In [ ]:
train_km.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
train_km.describe()

Avanti West Coast       c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000  6.000000            6.000000           6.000000   
mean           30.258496  6.605607            1.300215          11.056204   
std             5.799023  0.711503            0.204546           1.817135   
min            23.756465  5.908183            0.889568           9.071378   
25%            25.598492  5.976334            1.330623           9.478666   
50%            30.491876  6.587425            1.388080          11.064264   
75%            35.290925  7.259233            1.399611          12.668371   
max            35.952790  7.294806            1.420639          12.984113   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean      26.584799              22.166479                 60.866318   
std        6.669206               1.481813                  4.987773   
min       19.479801              19.167262                 54.698701   
25%       20.829172              22.499114                 57.979962   
50%       26.985722              22.762515                 60.385972   
75%       32.628156              22.887209                 62.709046   
max       32.771591              22.966493                 69.065904   

       Grand Central  Great Western Railway  Greater Anglia  ...      Lumo  \
count       6.000000               6.000000        6.000000  ...  2.000000   
mean        2.154388              42.063688       26.892697  ...  1.341263   
std         0.690120               3.160970        2.003531  ...  0.956560   
min         0.779314              35.946496       24.665694  ...  0.664873   
25%         2.212259              42.410639       25.126722  ...  1.003068   
50%         2.460149              42.831656       27.094759  ...  1.341263   
75%         2.529543              43.192482       28.502380  ...  1.679458   
max         2.544411              45.189260       29.058676  ...  2.017653   

       Merseyrail  Northern Trains   ScotRail  South Western Railway  \
count    6.000000         6.000000   6.000000               6.000000   
mean     5.775167        47.385366  42.886781              35.106025   
std      0.818646         5.517824   5.742935               4.476003   
min      4.295194        39.793827  35.864820              28.575964   
25%      5.554219        44.887699  38.646972              32.396570   
50%      6.044646        47.512826  43.088416              35.754636   
75%      6.299780        48.681173  47.575683              38.905902   
max      6.490946        56.409438  49.041104              39.317375   

       Southeastern   TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000   6.000000              6.000000              6.000000   
mean      31.881571  21.704755             16.792264             23.783343   
std        3.074508   2.731123              3.734661              2.849562   
min       28.972025  17.091445             12.044987             20.435191   
25%       29.420222  20.479125             13.984868             21.641429   
50%       30.913336  22.669665             16.767981             23.682489   
75%       34.535609  23.807824             19.946065             25.477298   
max       35.825177  23.861598             21.110044             27.863244   

       Elizabeth line  
count        6.000000  
mean         6.086186  
std          2.711115  
min          2.822836  
25%          4.315854  
50%          5.601479  
75%          7.803860  
max         10.066020  

[8 rows x 24 columns]

In [ ]:
train_km[train_km.isin([train_km.max().max()])].stack()

Time period                                   
Apr 2019 to Mar 2020  Govia Thameslink Railway    69.065904
dtype: float64

In [ ]:
train_km[train_km.isin([train_km.min().min()])].stack()

Time period                      
Apr 2020 to Mar 2021  Hull Trains    0.299471
dtype: float64

Govia Thameslink trains travelled the most, as they had the greatest number passenger train kilometres between Apr 2019 to Mar 2020 with 69 million train kilometres.

Heathrow Express had the lowest between Apr 2020 to Mar 2021 with less than 300 thousand train kilometres

In [ ]:
total_train_km = train_km.sum(axis=1)

In [ ]:
total_train_km[total_train_km.isin([total_train_km.max().max()])]

Time period
Apr 2019 to Mar 2020    558.396597
dtype: float64

In [ ]:
total_train_km[total_train_km.isin([total_train_km.min().min()])]

Time period
Apr 2020 to Mar 2021    424.273842
dtype: float64

Trains were travelling the most between April 2019 and March 2020, with 550 million km travelled. The least was on the year after, with 418 million km.

## Distance per journey

Which TOC passenger travels the farthest per journey annually?

In [ ]:
km_per_journey = passenger_km/journeys

In [ ]:
km_per_journey

Avanti West Coast        c2c  Caledonian Sleeper  \
Time period                                                              
Apr 2017 to Mar 2018         198.049175  25.313978          651.703724   
Apr 2018 to Mar 2019         194.373209  25.188436          658.550580   
Apr 2019 to Mar 2020         197.150934  25.379454          654.238497   
Apr 2020 to Mar 2021         187.556660  21.944595          742.717967   
Apr 2021 to Mar 2022         196.015272  22.165530          675.986682   
Apr 2022 to Mar 2023         191.679003  22.932143          659.417549   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018          56.876593     93.719934              90.179524   
Apr 2018 to Mar 2019          56.352166     91.416264              90.336285   
Apr 2019 to Mar 2020          55.633171     91.476583              88.605009   
Apr 2020 to Mar 2021          46.315103     83.188812              80.957713   
Apr 2021 to Mar 2022          52.580680     87.987766              82.707658   
Apr 2022 to Mar 2023          54.367218     87.429774              86.012612   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018                 27.442148     279.733991   
Apr 2018 to Mar 2019                 26.960569     277.988774   
Apr 2019 to Mar 2020                 26.780886     276.314277   
Apr 2020 to Mar 2021                 23.347440     259.009264   
Apr 2021 to Mar 2022                 26.231603     275.456923   
Apr 2022 to Mar 2023                 27.314955     269.818150   

                      Great Western Railway  Greater Anglia  ...        Lumo  \
Time period                                                  ...               
Apr 2017 to Mar 2018              57.792405       46.745188  ...         NaN   
Apr 2018 to Mar 2019              59.980718       46.208272  ...         NaN   
Apr 2019 to Mar 2020              61.471591       45.539331  ...         NaN   
Apr 2020 to Mar 2021              61.652761       39.835089  ...         NaN   
Apr 2021 to Mar 2022              68.993425       42.396585  ...  474.920181   
Apr 2022 to Mar 2023              69.578604       43.195733  ...  468.979931   

                      Merseyrail  Northern Trains   ScotRail  \
Time period                                                    
Apr 2017 to Mar 2018   18.001636        25.029036  30.263542   
Apr 2018 to Mar 2019   17.816488        25.504653  30.464773   
Apr 2019 to Mar 2020   18.159700        26.789685  30.167804   
Apr 2020 to Mar 2021   18.293257        26.986905  27.574314   
Apr 2021 to Mar 2022   18.178454        29.642194  31.555911   
Apr 2022 to Mar 2023   17.705995        30.398778  32.216612   

                      South Western Railway  Southeastern   TfW Rail  \
Time period                                                            
Apr 2017 to Mar 2018              28.033064     25.810148  37.870632   
Apr 2018 to Mar 2019              27.963765     25.610726  37.149750   
Apr 2019 to Mar 2020              28.016369     25.789861  36.758091   
Apr 2020 to Mar 2021              24.320167     24.775036  37.161214   
Apr 2021 to Mar 2022              28.177756     26.002231  41.634269   
Apr 2022 to Mar 2023              29.024640     26.762869  42.201179   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018             72.178130             37.409809   
Apr 2018 to Mar 2019             71.178416             37.100841   
Apr 2019 to Mar 2020             72.004662             39.571468   
Apr 2020 to Mar 2021             73.781312             39.379638   
Apr 2021 to Mar 2022             73.392831             40.398019   
Apr 2022 to Mar 2023             72.864370             40.82

In [ ]:
km_per_journey[km_per_journey.isin([km_per_journey.min().min()])].stack()

Time period                            
Apr 2020 to Mar 2021  London Overground    6.796264
dtype: float64

In [ ]:
km_per_journey[km_per_journey.isin([km_per_journey.max().max()])].stack()

Time period                             
Apr 2020 to Mar 2021  Caledonian Sleeper    742.717967
dtype: float64

London Overgound had the shortest journeys, averaging at 6.8km per journey in 2020-2021. The longest journeys are operated by Caledonian Sleeper with 742km per journey in 2020-2021

## Complaints closed

In [ ]:
complaints = data_tables["Complaints closed"]

In [ ]:
complaints.shape

(6, 24)

In [ ]:
complaints.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
complaints.describe()

Avanti West Coast           c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000      6.000000            6.000000           6.000000   
mean        50010.000000   8934.833333          698.833333        4380.833333   
std         20472.457332   4932.995821          348.106545        2386.953156   
min         17484.000000   3405.000000          284.000000        1422.000000   
25%         38798.250000   5329.750000          422.750000        2484.250000   
50%         55516.500000   8315.000000          730.000000        4655.500000   
75%         63756.750000  11594.250000         1010.250000        6466.750000   
max         71814.000000  16552.000000         1025.000000        6721.000000   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean   16371.166667           12833.833333              38929.666667   
std    10424.880573            5443.148442              15918.150127   
min     3994.000000            2768.000000              16295.000000   
25%     8131.000000           11830.000000              29468.000000   
50%    16659.500000           14704.000000              40522.000000   
75%    25765.500000           15519.250000              51840.750000   
max    26825.000000           18164.000000              54842.000000   

       Grand Central  Great Western Railway  Greater Anglia  ...         Lumo  \
count       6.000000               6.000000        6.000000  ...     2.000000   
mean     1935.500000           43015.166667    24369.500000  ...  1923.500000   
std      1189.140656           18590.716914    13818.915974  ...   996.313455   
min       253.000000           15553.000000     7669.000000  ...  1219.000000   
25%      1286.000000           30958.250000    14255.000000  ...  1571.250000   
50%      1964.000000           46965.500000    23909.000000  ...  1923.500000   
75%      2516.750000           56240.000000    32575.250000  ...  2275.750000   
max      3671.000000           63653.000000    44229.000000  ...  2628.000000   

        Merseyrail  Northern Trains      ScotRail  South Western Railway  \
count     6.000000         6.000000      6.000000               6.000000   
mean   2352.833333     21718.333333  20127.333333           35714.166667   
std    1246.269219     14432.097223   8858.917804           15397.536263   
min    1028.000000      5850.000000   7264.000000           14404.000000   
25%    1365.500000     14729.500000  15106.500000           25460.000000   
50%    2121.500000     15784.000000  20332.500000           37154.500000   
75%    3494.750000     29633.500000  27173.250000           48556.500000   
max    3780.000000     44264.000000  30017.000000           51653.000000   

       Southeastern     TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000      6.00000              6.000000              6.000000   
mean   31120.333333  16541.50000          13708.000000          19033.666667   
std    16465.772374   5999.84269           5680.839515           7846.268022   
min    10487.000000   5793.00000           5139.000000           7484.000000   
25%    20648.500000  14688.50000          10348.750000          15954.750000   
50%    28645.500000  18441.00000          14793.500000          18190.500000   
75%    43346.000000  20580.25000          17509.500000          23024.250000   
max    52715.000000  21843.00000          20240.000000          30492.000000   

       Elizabeth line  
count        6.000000  
mean       939.500000  
std        360.729677  
min        402.000000  
25%        701.750000  
50%       1034.000000  
75%       1225.250000  
max       1287.000000  

[8 rows x 24 columns]

In [ ]:
complaints[complaints.isin([complaints.max().max()])].stack()

Time period                            
Apr 2019 to Mar 2020  Avanti West Coast    71814.0
dtype: float64

In [ ]:
complaints[complaints.isin([complaints.min().min()])].stack()

Time period                      
Apr 2020 to Mar 2021  Hull Trains    108.0
dtype: float64

Avanti West Coast had the most amount of complaints closed with 71814 during the time period between April 2019 and March 2020.

Hull trains had the least complaints closed, with 108 between April 2020 and March 2021

In [ ]:
total_complaints = complaints.sum(axis=1)

In [ ]:
total_complaints[total_complaints.isin([total_complaints.max().max()])]

Time period
Apr 2018 to Mar 2019    536272.0
dtype: float64

In [ ]:
total_complaints[total_complaints.isin([total_complaints.min().min()])]

Time period
Apr 2020 to Mar 2021    133003.0
dtype: float64

Total compliants closed occured the most between April 2018 and March 2019. The least occured between April 2020 to March 2021

## Passenger assists

In [ ]:
assists = data_tables["Passenger assists"]
assists

Avanti West Coast     c2c  Caledonian Sleeper  \
Time period                                                           
Apr 2017 to Mar 2018           117358.0  1217.0                 0.0   
Apr 2018 to Mar 2019           105649.0  1057.0                 0.0   
Apr 2019 to Mar 2020            98913.0   822.0                 0.0   
Apr 2020 to Mar 2021            11749.0   109.0                 0.0   
Apr 2021 to Mar 2022            61321.0  1185.0                 0.0   
Apr 2022 to Mar 2023            88808.0  3154.0                 0.0   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018            15371.0           0.0                59835.0   
Apr 2018 to Mar 2019            17068.0           0.0                63312.0   
Apr 2019 to Mar 2020            16960.0           0.0                62946.0   
Apr 2020 to Mar 2021             1596.0           0.0                 7733.0   
Apr 2021 to Mar 2022             9296.0           0.0                42230.0   
Apr 2022 to Mar 2023            16309.0           0.0                66669.0   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018                   51125.0            0.0   
Apr 2018 to Mar 2019                   57060.0            0.0   
Apr 2019 to Mar 2020                   52487.0            0.0   
Apr 2020 to Mar 2021                    7821.0            0.0   
Apr 2021 to Mar 2022                   36206.0            0.0   
Apr 2022 to Mar 2023                   88374.0            0.0   

                      Great Western Railway  Greater Anglia  ...  Lumo  \
Time period                                                  ...         
Apr 2017 to Mar 2018               165698.0         36041.0  ...   NaN   
Apr 2018 to Mar 2019               162199.0         38657.0  ...   NaN   
Apr 2019 to Mar 2020               154909.0         36875.0  ...   NaN   
Apr 2020 to Mar 2021                17014.0          4519.0  ...   NaN   
Apr 2021 to Mar 2022                88640.0         23811.0  ...   0.0   
Apr 2022 to Mar 2023               138862.0         41466.0  ...   0.0   

                      Merseyrail  Northern Trains  ScotRail  \
Time period                                                   
Apr 2017 to Mar 2018      5675.0          45172.0   68787.0   
Apr 2018 to Mar 2019      8677.0          47209.0   66981.0   
Apr 2019 to Mar 2020      5054.0          46960.0   64065.0   
Apr 2020 to Mar 2021       470.0           5668.0    6580.0   
Apr 2021 to Mar 2022      2576.0          31633.0   40174.0   
Apr 2022 to Mar 2023      3613.0          50688.0   59323.0   

                      South Western Railway  Southeastern  TfW Rail  \
Time period                                                           
Apr 2017 to Mar 2018                73073.0       27522.0   60084.0   
Apr 2018 to Mar 2019                71779.0       29625.0   60443.0   
Apr 2019 to Mar 2020                57659.0       28596.0   55580.0   
Apr 2020 to Mar 2021                 6819.0        6041.0    6215.0   
Apr 2021 to Mar 2022                37564.0       24781.0   35110.0   
Apr 2022 to Mar 2023                62634.0       55975.0   55479.0   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018               23836.0               38750.0   
Apr 2018 to Mar 2019               24270.0               52555.0   
Apr 2019 to Mar 2020               23252.0               50151.0   
Apr 2020 to Mar 2021                2531.0                4442.0   
Apr 2021 to Mar 2022               13887.0               27605.0   
Apr 2022 to Mar 2023               21807.0               43584.0   

                      Elizabeth line  
Time period                           
A

In [ ]:
assists.shape

(6, 24)

In [ ]:
assists.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
assists.describe()

Avanti West Coast          c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000     6.000000                 6.0           6.000000   
mean        80633.000000  1257.333333                 0.0       12766.666667   
std         38712.978976  1015.137560                 0.0        6200.734010   
min         11749.000000   109.000000                 0.0        1596.000000   
25%         68192.750000   880.750000                 0.0       10814.750000   
50%         93860.500000  1121.000000                 0.0       15840.000000   
75%        103965.000000  1209.000000                 0.0       16797.250000   
max        117358.000000  3154.000000                 0.0       17068.000000   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count           6.0               6.000000                  6.000000   
mean            0.0           50454.166667              48845.500000   
std             0.0           22649.616468              26424.244646   
min             0.0            7733.000000               7821.000000   
25%             0.0           46631.250000              39935.750000   
50%             0.0           61390.500000              51806.000000   
75%             0.0           63220.500000              55916.750000   
max             0.0           66669.000000              88374.000000   

       Grand Central  Great Western Railway  Greater Anglia  ...  Lumo  \
count            6.0               6.000000        6.000000  ...   2.0   
mean             0.0          121220.333333    30228.166667  ...   0.0   
std              0.0           58350.846858    13981.736894  ...   0.0   
min              0.0           17014.000000     4519.000000  ...   0.0   
25%              0.0          101195.500000    26868.500000  ...   0.0   
50%              0.0          146885.500000    36458.000000  ...   0.0   
75%              0.0          160376.500000    38211.500000  ...   0.0   
max              0.0          165698.000000    41466.000000  ...   0.0   

        Merseyrail  Northern Trains      ScotRail  South Western Railway  \
count     6.000000         6.000000      6.000000               6.000000   
mean   4344.166667     37888.333333  50985.000000           51588.000000   
std    2818.460957     17107.497218  24091.797816           25412.944733   
min     470.000000      5668.000000   6580.000000            6819.000000   
25%    2835.250000     35017.750000  44961.250000           42587.750000   
50%    4333.500000     46066.000000  61694.000000           60146.500000   
75%    5519.750000     47146.750000  66252.000000           69492.750000   
max    8677.000000     50688.000000  68787.000000           73073.000000   

       Southeastern      TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000      6.000000              6.000000              6.000000   
mean   28756.666667  45485.166667          18263.833333          36181.166667   
std    15968.402082  21393.621249           8616.700422          17919.736844   
min     6041.000000   6215.000000           2531.000000           4442.000000   
25%    25466.250000  40202.250000          15867.000000          30391.250000   
50%    28059.000000  55529.500000          22529.500000          41167.000000   
75%    29367.750000  58958.000000          23690.000000          48509.250000   
max    55975.000000  60443.000000          24270.000000          52555.000000   

       Elizabeth line  
count        6.000000  
mean      2159.500000  
std       1546.108243  
min        409.000000  
25%       1554.000000  
50%       2022.500000  
75%       2059.000000  
max       5034.000000  

[8 rows x 24 columns]

In [ ]:
assists[assists.isin([assists.max().max()])].stack()

Time period                                
Apr 2017 to Mar 2018  Great Western Railway    165698.0
dtype: float64

In [ ]:
assists[assists.isin([assists.min().min()])].stack()

Time period                             
Apr 2017 to Mar 2018  Caledonian Sleeper    0.0
                      CrossCountry          0.0
                      Grand Central         0.0
                      Hull Trains           0.0
Apr 2018 to Mar 2019  Caledonian Sleeper    0.0
                      CrossCountry          0.0
                      Grand Central         0.0
                      Hull Trains           0.0
Apr 2019 to Mar 2020  Caledonian Sleeper    0.0
                      CrossCountry          0.0
                      Grand Central         0.0
                      Hull Trains           0.0
Apr 2020 to Mar 2021  Caledonian Sleeper    0.0
                      CrossCountry          0.0
                      Grand Central         0.0
                      Hull Trains           0.0
Apr 2021 to Mar 2022  Caledonian Sleeper    0.0
                      CrossCountry          0.0
                      Grand Central         0.0
                      Hull Trains           0.0

The greatest number of passenger assists requested occurred with Great Western Railway, with 165,698 assists made between April 2017 to March 2018.

Many operators did not have any passenger assists.

In [ ]:
total_assists = assists.sum(axis=1)

In [ ]:
total_assists[total_assists.isin([total_assists.max().max()])]

Time period
Apr 2018 to Mar 2019    918163.0
dtype: float64

In [ ]:
total_assists[total_assists.isin([total_assists.min().min()])]

Time period
Apr 2020 to Mar 2021    102029.0
dtype: float64

Mosts assists were made during 2018 and 2019. Least occured between April 2020 to March 2021

## Delay compensation claims closed

In [ ]:
delay_compensations = data_tables["Delay compensation claims closed"]
delay_compensations

Avanti West Coast      c2c  Caledonian Sleeper  \
Time period                                                            
Apr 2018 to Mar 2019           433187.0  44213.0              5610.0   
Apr 2019 to Mar 2020           584426.0  20097.0             10166.0   
Apr 2020 to Mar 2021            46715.0   1161.0               661.0   
Apr 2021 to Mar 2022           267595.0   4852.0              2286.0   
Apr 2022 to Mar 2023           788608.0  17328.0              5925.0   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2018 to Mar 2019            20998.0      139176.0                68781.0   
Apr 2019 to Mar 2020            24561.0      166553.0               175939.0   
Apr 2020 to Mar 2021             2182.0       13001.0                14221.0   
Apr 2021 to Mar 2022             8715.0       63786.0               117286.0   
Apr 2022 to Mar 2023            65326.0      148005.0               276860.0   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2018 to Mar 2019                 1552957.0        10706.0   
Apr 2019 to Mar 2020                 1139323.0        11732.0   
Apr 2020 to Mar 2021                   76382.0          727.0   
Apr 2021 to Mar 2022                  288797.0         4493.0   
Apr 2022 to Mar 2023                  783123.0        27176.0   

                      Great Western Railway  Greater Anglia  ...     Lumo  \
Time period                                                  ...            
Apr 2018 to Mar 2019               162022.0        426758.0  ...      NaN   
Apr 2019 to Mar 2020               381130.0        593721.0  ...      NaN   
Apr 2020 to Mar 2021                31694.0         26513.0  ...      NaN   
Apr 2021 to Mar 2022               302289.0         80700.0  ...   4420.0   
Apr 2022 to Mar 2023               762312.0        226794.0  ...  26341.0   

                      Merseyrail  Northern Trains  ScotRail  \
Time period                                                   
Apr 2018 to Mar 2019      1362.0         246484.0  142462.0   
Apr 2019 to Mar 2020       988.0         364689.0  117004.0   
Apr 2020 to Mar 2021       116.0          22836.0    7110.0   
Apr 2021 to Mar 2022       943.0          98934.0   30455.0   
Apr 2022 to Mar 2023      1464.0         232571.0   69821.0   

                      South Western Railway  Southeastern  TfW Rail  \
Time period                                                           
Apr 2018 to Mar 2019               763866.0      452481.0   22908.0   
Apr 2019 to Mar 2020               755515.0      559883.0   73421.0   
Apr 2020 to Mar 2021                25478.0       44868.0    3745.0   
Apr 2021 to Mar 2022               155877.0      139134.0   35773.0   
Apr 2022 to Mar 2023               395038.0      677415.0  114023.0   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2018 to Mar 2019              158056.0              223230.0   
Apr 2019 to Mar 2020              247507.0              535162.0   
Apr 2020 to Mar 2021               12337.0               23886.0   
Apr 2021 to Mar 2022               82131.0              111174.0   
Apr 2022 to Mar 2023              256065.0              286143.0   

                      Elizabeth line  
Time period                           
Apr 2018 to Mar 2019          6461.0  
Apr 2019 to Mar 2020          9713.0  
Apr 2020 to Mar 2021          1180.0  
Apr 2021 to Mar 2022          3962.0  
Apr 2022 to Mar 2023          9374.0  

[5 rows x 24 columns]

In [ ]:
delay_compensations.shape

(5, 24)

In [ ]:
delay_compensations.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Apr 2018 to Mar 2019 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             5 non-null      float64
 1   c2c                           5 non-null      float64
 2   Caledonian Sleeper            5 non-null      float64
 3   Chiltern Railways             5 non-null      float64
 4   CrossCountry                  5 non-null      float64
 5   East Midlands Railway         5 non-null      float64
 6   Govia Thameslink Railway      5 non-null      float64
 7   Grand Central                 5 non-null      float64
 8   Great Western Railway         5 non-null      float64
 9   Greater Anglia                5 non-null      float64
 10  Heathrow Express              5 non-null      float64
 11  Hull Trains                   5 non-null      float64
 12  London North Eastern Railway  5 non

In [ ]:
delay_compensations.describe()

Avanti West Coast           c2c  Caledonian Sleeper  Chiltern Railways  \
count           5.000000      5.000000            5.000000           5.000000   
mean       424106.200000  17530.200000         4929.600000       24356.400000   
std        285292.102487  16935.824654         3677.064631       24628.166016   
min         46715.000000   1161.000000          661.000000        2182.000000   
25%        267595.000000   4852.000000         2286.000000        8715.000000   
50%        433187.000000  17328.000000         5610.000000       20998.000000   
75%        584426.000000  20097.000000         5925.000000       24561.000000   
max        788608.000000  44213.000000        10166.000000       65326.000000   

        CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count       5.000000               5.000000              5.000000e+00   
mean   106104.200000          130617.400000              7.681164e+05   
std     65120.108874          101230.595678              6.046151e+05   
min     13001.000000           14221.000000              7.638200e+04   
25%     63786.000000           68781.000000              2.887970e+05   
50%    139176.000000          117286.000000              7.831230e+05   
75%    148005.000000          175939.000000              1.139323e+06   
max    166553.000000          276860.000000              1.552957e+06   

       Grand Central  Great Western Railway  Greater Anglia  ...         Lumo  \
count       5.000000               5.000000        5.000000  ...      2.00000   
mean    10966.800000          327889.400000   270897.200000  ...  15380.50000   
std     10126.145649          277243.866805   237882.060679  ...  15500.48775   
min       727.000000           31694.000000    26513.000000  ...   4420.00000   
25%      4493.000000          162022.000000    80700.000000  ...   9900.25000   
50%     10706.000000          302289.000000   226794.000000  ...  15380.50000   
75%     11732.000000          381130.000000   426758.000000  ...  20860.75000   
max     27176.000000          762312.000000   593721.000000  ...  26341.00000   

       Merseyrail  Northern Trains       ScotRail  South Western Railway  \
count     5.00000         5.000000       5.000000               5.000000   
mean    974.60000    193102.800000   73370.400000          419154.800000   
std     531.02806    133891.431233   56838.170812          337950.528341   
min     116.00000     22836.000000    7110.000000           25478.000000   
25%     943.00000     98934.000000   30455.000000          155877.000000   
50%     988.00000    232571.000000   69821.000000          395038.000000   
75%    1362.00000    246484.000000  117004.000000          755515.000000   
max    1464.00000    364689.000000  142462.000000          763866.000000   

        Southeastern       TfW Rail  TransPennine Express  \
count       5.000000       5.000000               5.00000   
mean   374756.200000   49974.000000          151219.20000   
std    272148.613566   43941.419549          105323.51221   
min     44868.000000    3745.000000           12337.00000   
25%    139134.000000   22908.000000           82131.00000   
50%    452481.000000   35773.000000          158056.00000   
75%    559883.000000   73421.000000          247507.00000   
max    677415.000000  114023.000000          256065.00000   

       West Midlands Trains  Elizabeth line  
count              5.000000        5.000000  
mean          235919.000000     6138.000000  
std           195415.673668     3628.821778  
min            23886.000000     1180.000000  
25%           111174.000000     3962.000000  
50%           223230.000000     6461.000000  
75%           286143.000000     9374.000000  
max           535162.000000     9713.000000  

[8 rows x 24 columns]

In [ ]:
delay_compensations[delay_compensations.isin([delay_compensations.max().max()])].stack()

Time period                                   
Apr 2018 to Mar 2019  Govia Thameslink Railway    1552957.0
dtype: float64

In [ ]:
delay_compensations[delay_compensations.isin([delay_compensations.min().min()])].stack()

Time period                     
Apr 2020 to Mar 2021  Merseyrail    116.0
dtype: float64

Govia Thameslink Railway closed the most delay compensation claims, with 1,552,957 claims closed between April 2018 to March 2019.

Merseyrail had the least, with 116 between April 2020 to March 2021

In [ ]:
total_delay_compensations = delay_compensations.sum(axis=1)

In [ ]:
total_delay_compensations[total_delay_compensations.isin([total_delay_compensations.max().max()])]

Time period
Apr 2019 to Mar 2020    6272112.0
dtype: float64

In [ ]:
total_delay_compensations[total_delay_compensations.isin([total_delay_compensations.min().min()])]

Time period
Apr 2020 to Mar 2021    394948.0
dtype: float64

Country-wide the most total delay compensation claims closed occurred between April 2019 to March 2020, with 6,272,112.

The least claims closed occured between April 2020 to March 2021, with 394,948.


## Cancellations score

Cancellation score is a weighted score which counts full cancellations as one and part cancellations as half

In [ ]:
cancellation_score = data_tables["Cancellations score (percentage)"]
cancellation_score

Avanti West Coast       c2c  Caledonian Sleeper  \
Time period                                                             
Apr 2017 to Mar 2018           2.800000  1.700000            2.600000   
Apr 2018 to Mar 2019           1.644249  2.002229            1.600186   
Apr 2019 to Mar 2020           2.927638  1.604718            3.487817   
Apr 2020 to Mar 2021           2.026566  1.032676            3.785047   
Apr 2021 to Mar 2022           3.898613  1.323802            5.507792   
Apr 2022 to Mar 2023           9.060208  1.914077            2.658228   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018           1.200000      2.500000               1.300000   
Apr 2018 to Mar 2019           1.255472      2.720392               1.493196   
Apr 2019 to Mar 2020           1.384321      3.577390               1.736318   
Apr 2020 to Mar 2021           1.513793      1.639119               1.677328   
Apr 2021 to Mar 2022           1.964448      2.779838               2.884499   
Apr 2022 to Mar 2023           1.947729      6.496538               2.930958   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018                  4.400000       3.200000   
Apr 2018 to Mar 2019                  4.957649       3.802615   
Apr 2019 to Mar 2020                  4.482582       3.335557   
Apr 2020 to Mar 2021                  3.391537       2.802198   
Apr 2021 to Mar 2022                  5.734888       2.743446   
Apr 2022 to Mar 2023                  6.060887       5.238927   

                      Great Western Railway  Greater Anglia  ...      Lumo  \
Time period                                                  ...             
Apr 2017 to Mar 2018               3.000000        2.400000  ...       NaN   
Apr 2018 to Mar 2019               2.677942        2.458113  ...       NaN   
Apr 2019 to Mar 2020               2.550659        3.189486  ...       NaN   
Apr 2020 to Mar 2021               1.489119        1.863722  ...       NaN   
Apr 2021 to Mar 2022               3.035031        1.833490  ...  3.107020   
Apr 2022 to Mar 2023               3.251138        1.541427  ...  3.226269   

                      Merseyrail  Northern Trains  ScotRail  \
Time period                                                   
Apr 2017 to Mar 2018    1.200000         1.700000  2.300000   
Apr 2018 to Mar 2019    1.317301         2.952958  2.942261   
Apr 2019 to Mar 2020    1.030280         4.108027  2.495408   
Apr 2020 to Mar 2021    1.168108         1.348313  2.088879   
Apr 2021 to Mar 2022    1.109340         3.304470  2.776524   
Apr 2022 to Mar 2023    2.247432         4.214897  2.914607   

                      South Western Railway  Southeastern  TfW Rail  \
Time period                                                           
Apr 2017 to Mar 2018               2.900000      2.100000  1.900000   
Apr 2018 to Mar 2019               2.566867      2.484837  1.912446   
Apr 2019 to Mar 2020               3.812547      2.468837  2.785119   
Apr 2020 to Mar 2021               1.886999      1.786665  1.836915   
Apr 2021 to Mar 2022               2.807268      2.251868  4.026293   
Apr 2022 to Mar 2023               2.735081      2.770670  4.490828   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018              3.200000              2.600000   
Apr 2018 to Mar 2019              6.121791              2.171462   
Apr 2019 to Mar 2020              7.838039              5.121329   
Apr 2020 to Mar 2021              2.192412              2.222935   
Apr 2021 to Mar 2022              3.000302              4.745010   
Apr 2022 to Mar 2023              6.595656              4.258802   

                      Elizabeth

In [ ]:
cancellation_score.shape

(6, 24)

In [ ]:
cancellation_score.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
cancellation_score.describe()

Avanti West Coast       c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000  6.000000            6.000000           6.000000   
mean            3.726212  1.596250            3.273178           1.544294   
std             2.727643  0.365654            1.336549           0.336977   
min             1.644249  1.032676            1.600186           1.200000   
25%             2.219925  1.394031            2.614557           1.287684   
50%             2.863819  1.652359            3.073022           1.449057   
75%             3.655869  1.860557            3.710739           1.839245   
max             9.060208  2.002229            5.507792           1.964448   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean       3.285546               2.003717                  4.837924   
std        1.691070               0.716859                  0.972070   
min        1.639119               1.300000                  3.391537   
25%        2.555098               1.539229                  4.420646   
50%        2.750115               1.706823                  4.720116   
75%        3.378002               2.597454                  5.540578   
max        6.496538               2.930958                  6.060887   

       Grand Central  Great Western Railway  Greater Anglia  ...      Lumo  \
count       6.000000               6.000000        6.000000  ...  2.000000   
mean        3.520457               2.667315        2.214373  ...  3.166644   
std         0.926205               0.630652        0.594238  ...  0.084322   
min         2.743446               1.489119        1.541427  ...  3.107020   
25%         2.901648               2.582480        1.841048  ...  3.136832   
50%         3.267779               2.838971        2.131861  ...  3.166644   
75%         3.685850               3.026273        2.443585  ...  3.196457   
max         5.238927               3.251138        3.189486  ...  3.226269   

       Merseyrail  Northern Trains  ScotRail  South Western Railway  \
count    6.000000         6.000000  6.000000               6.000000   
mean     1.345410         2.938111  2.586280               2.784794   
std      0.452117         1.199475  0.348808               0.620653   
min      1.030280         1.348313  2.088879               1.886999   
25%      1.124032         2.013239  2.348852               2.608921   
50%      1.184054         3.128714  2.635966               2.771174   
75%      1.287976         3.907138  2.880086               2.876817   
max      2.247432         4.214897  2.942261               3.812547   

       Southeastern  TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000  6.000000              6.000000              6.000000   
mean       2.310479  2.825267              4.824700              3.519923   
std        0.343328  1.173403              2.314993              1.338511   
min        1.786665  1.836915              2.192412              2.171462   
25%        2.137967  1.903111              3.050227              2.317201   
50%        2.360352  2.348782              4.660896              3.429401   
75%        2.480837  3.716000              6.477190              4.623458   
max        2.770670  4.490828              7.838039              5.121329   

       Elizabeth line  
count        6.000000  
mean         2.338056  
std          0.760451  
min          1.581593  
25%          1.814131  
50%          2.314247  
75%          2.431681  
max          3.700000  

[8 rows x 24 columns]

In [ ]:
cancellation_score[cancellation_score.isin([cancellation_score.max().max()])].stack()

Time period                            
Apr 2022 to Mar 2023  Avanti West Coast    9.060208
dtype: float64

In [ ]:
cancellation_score[cancellation_score.isin([cancellation_score.min().min()])].stack()

Time period                     
Apr 2019 to Mar 2020  Merseyrail    1.03028
dtype: float64

The highest cancellation score was with TransPennine Express during April 2019 - March 2020.
Merseyrail managed to achieve the lowest score with 1.0 during April 2019 - March 2020, with c2c achieving the same score a year after.


In [ ]:
total_cancellation_score = cancellation_score.mean(axis=1)

In [ ]:
total_cancellation_score[total_cancellation_score.isin([total_cancellation_score.max().max()])]

Time period
Apr 2022 to Mar 2023    3.8332
dtype: float64

In [ ]:
total_cancellation_score[total_cancellation_score.isin([total_cancellation_score.min().min()])]

Time period
Apr 2020 to Mar 2021    2.040391
dtype: float64

In the last six years, Apr 2022 to Mar 2023 saw the highest cancellation score on average with 3.83. The lowest was seen between April 2020 - March 2021 after with 2.04

## Trains planned

In [ ]:
trains_planned = data_tables["Trains planned"]
trains_planned

Avanti West Coast       c2c  Caledonian Sleeper  \
Time period                                                             
Apr 2017 to Mar 2018           102011.0  125172.0              2130.0   
Apr 2018 to Mar 2019           103117.0  125610.0              2156.0   
Apr 2019 to Mar 2020           102540.0  123355.0              2093.0   
Apr 2020 to Mar 2021            76262.0  101145.0              1070.0   
Apr 2021 to Mar 2022            74270.0  104283.0              1861.0   
Apr 2022 to Mar 2023            72399.0  102347.0              1975.0   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018           141770.0      101891.0               159542.0   
Apr 2018 to Mar 2019           141859.0      103974.0               159758.0   
Apr 2019 to Mar 2020           138660.0      101848.0               159101.0   
Apr 2020 to Mar 2021           103746.0       61771.0               134917.0   
Apr 2021 to Mar 2022           110260.0       75508.0               157497.0   
Apr 2022 to Mar 2023           100399.0       75394.0               153414.0   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018                 1141572.0         6320.0   
Apr 2018 to Mar 2019                 1248616.0         6272.0   
Apr 2019 to Mar 2020                 1358603.0         5996.0   
Apr 2020 to Mar 2021                 1106696.0         1820.0   
Apr 2021 to Mar 2022                 1071442.0         5340.0   
Apr 2022 to Mar 2023                 1029379.0         6299.0   

                      Great Western Railway  Greater Anglia  ...    Lumo  \
Time period                                                  ...           
Apr 2017 to Mar 2018               532499.0        434668.0  ...     NaN   
Apr 2018 to Mar 2019               533376.0        430025.0  ...     NaN   
Apr 2019 to Mar 2020               536724.0        438613.0  ...     NaN   
Apr 2020 to Mar 2021               429247.0        384097.0  ...     NaN   
Apr 2021 to Mar 2022               499929.0        405429.0  ...   869.0   
Apr 2022 to Mar 2023               505423.0        381854.0  ...  3487.0   

                      Merseyrail  Northern Trains  ScotRail  \
Time period                                                   
Apr 2017 to Mar 2018    210047.0         845770.0  758700.0   
Apr 2018 to Mar 2019    209747.0         861289.0  770088.0   
Apr 2019 to Mar 2020    203828.0         939429.0  796483.0   
Apr 2020 to Mar 2021    137102.0         659639.0  589024.0   
Apr 2021 to Mar 2022    170011.0         773770.0  624630.0   
Apr 2022 to Mar 2023    191018.0         696482.0  630634.0   

                      South Western Railway  Southeastern  TfW Rail  \
Time period                                                           
Apr 2017 to Mar 2018               581565.0      640978.0  329834.0   
Apr 2018 to Mar 2019               576364.0      654389.0  329944.0   
Apr 2019 to Mar 2020               582301.0      633760.0  338262.0   
Apr 2020 to Mar 2021               479783.0      527855.0  218328.0   
Apr 2021 to Mar 2022               520987.0      523965.0  259457.0   
Apr 2022 to Mar 2023               510515.0      511970.0  308707.0   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018               85351.0              423384.0   
Apr 2018 to Mar 2019              105492.0              434569.0   
Apr 2019 to Mar 2020              116732.0              432378.0   
Apr 2020 to Mar 2021               79912.0              328957.0   
Apr 2021 to Mar 2022               96007.0              390505.0   
Apr 2022 to Mar 2023               79143.0              365361.0   

                      Elizabeth line  
Time per

In [ ]:
trains_planned.shape

(6, 24)

In [ ]:
trains_planned.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
trains_planned.describe()

Avanti West Coast            c2c  Caledonian Sleeper  \
count           6.000000       6.000000            6.000000   
mean        88433.166667  113652.000000         1880.833333   
std         15522.901500   12180.793143          412.195787   
min         72399.000000  101145.000000         1070.000000   
25%         74768.000000  102831.000000         1889.500000   
50%         89136.500000  113819.000000         2034.000000   
75%        102407.750000  124717.750000         2120.750000   
max        103117.000000  125610.000000         2156.000000   

       Chiltern Railways   CrossCountry  East Midlands Railway  \
count           6.000000       6.000000               6.000000   
mean       122782.333333   86731.000000          154038.166667   
std         19983.770542   18072.936873            9660.363170   
min        100399.000000   61771.000000          134917.000000   
25%        105374.500000   75422.500000          154434.750000   
50%        124460.000000   88678.000000          158299.000000   
75%        140992.500000  101880.250000          159431.750000   
max        141859.000000  103974.000000          159758.000000   

       Govia Thameslink Railway  Grand Central  Great Western Railway  \
count              6.000000e+00       6.000000               6.000000   
mean               1.159385e+06    5341.166667          506199.666667   
std                1.227835e+05    1764.620800           40800.932174   
min                1.029379e+06    1820.000000          429247.000000   
25%                1.080256e+06    5504.000000          501302.500000   
50%                1.124134e+06    6134.000000          518961.000000   
75%                1.221855e+06    6292.250000          533156.750000   
max                1.358603e+06    6320.000000          536724.000000   

       Greater Anglia  ...         Lumo     Merseyrail  Northern Trains  \
count        6.000000  ...     2.000000       6.000000         6.000000   
mean    412447.666667  ...  2178.000000  186958.833333    796063.166667   
std      25598.144274  ...  1851.205553   28727.486778    106116.811172   
min     381854.000000  ...   869.000000  137102.000000    659639.000000   
25%     389430.000000  ...  1523.500000  175262.750000    715804.000000   
50%     417727.000000  ...  2178.000000  197423.000000    809770.000000   
75%     433507.250000  ...  2832.500000  208267.250000    857409.250000   
max     438613.000000  ...  3487.000000  210047.000000    939429.000000   

            ScotRail  South Western Railway   Southeastern       TfW Rail  \
count       6.000000               6.000000       6.000000       6.000000   
mean   694926.500000          541919.166667  582152.833333  297422.000000   
std     89800.329678           43986.842580   67233.135293   48167.784076   
min    589024.000000          479783.000000  511970.000000  218328.000000   
25%    626131.000000          513133.000000  524937.500000  271769.500000   
50%    694667.000000          548675.500000  580807.500000  319270.500000   
75%    767241.000000          580264.750000  639173.500000  329916.500000   
max    796483.000000          582301.000000  654389.000000  338262.000000   

       TransPennine Express  West Midlands Trains  Elizabeth line  
count              6.000000              6.000000        6.000000  
mean           93772.833333         395859.000000   177909.666667  
std            15142.890760          42483.874611    58671.560670  
min            79143.000000         328957.000000   132510.000000  
25%            81271.750000         371647.000000   139354.750000  
50%            90679.000000         406944.500000   160351.500000  
75%           103120.750000         430129.500000   184472.750000  
max           116732.000000         434569.000000   289376.000000  

[8 rows x 24 columns]

In [ ]:
trains_planned[trains_planned.isin([trains_planned.max().max()])].stack()

Time period                                   
Apr 2019 to Mar 2020  Govia Thameslink Railway    1358603.0
dtype: float64

In [ ]:
trains_planned[trains_planned.isin([trains_planned.min().min()])].stack()

Time period                      
Apr 2020 to Mar 2021  Hull Trains    506.0
dtype: float64

Govia Thameslink Railway had the most trains planned in one year, with 1,358,603 trains planned between April 2019 and March 2020. Contrast to this is Hull Trains that planned only 506 between April 2020 to March 2021.

In [ ]:
total_trains_planned = trains_planned.sum(axis=1)

In [ ]:
total_trains_planned[total_trains_planned.isin([total_trains_planned.max().max()])]

Time period
Apr 2019 to Mar 2020    7794211.0
dtype: float64

In [ ]:
total_trains_planned[total_trains_planned.isin([total_trains_planned.min().min()])]

Time period
Apr 2020 to Mar 2021    6106487.0
dtype: float64

Most total trains planned in the country occured from April 2019 to March 2020 with 7,794,211 trains planned. The least trains planned occured between April 2020 to March 2021 with 6,106,487 trains.

## On Time Trains

On Time punctuality measure: the percentage of recorded station stops arrived at ‘on time’ (early or less than one minute after the scheduled time)

In [ ]:
on_time = data_tables["On Time (percentage)"]
on_time

Avanti West Coast        c2c  Caledonian Sleeper  \
Time period                                                              
Apr 2017 to Mar 2018          49.600000  83.500000           65.900000   
Apr 2018 to Mar 2019          46.657664  82.486609           67.363874   
Apr 2019 to Mar 2020          39.558502  82.527540           61.654784   
Apr 2020 to Mar 2021          61.786970  84.897879           74.365140   
Apr 2021 to Mar 2022          52.971283  83.478569           68.343689   
Apr 2022 to Mar 2023          40.786618  77.848792           68.074650   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018          69.100000     46.700000              60.700000   
Apr 2018 to Mar 2019          68.347633     45.612256              57.524479   
Apr 2019 to Mar 2020          67.163523     46.991776              57.971378   
Apr 2020 to Mar 2021          80.173556     69.206661              75.175995   
Apr 2021 to Mar 2022          74.237213     60.051950              58.236430   
Apr 2022 to Mar 2023          71.579636     50.229068              53.805982   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018                 61.100000      50.900000   
Apr 2018 to Mar 2019                 69.094686      49.677204   
Apr 2019 to Mar 2020                 70.876339      49.349666   
Apr 2020 to Mar 2021                 80.083372      69.318600   
Apr 2021 to Mar 2022                 74.921285      56.469856   
Apr 2022 to Mar 2023                 68.415763      47.021357   

                      Great Western Railway  Greater Anglia  ...       Lumo  \
Time period                                                  ...              
Apr 2017 to Mar 2018              57.600000       63.800000  ...        NaN   
Apr 2018 to Mar 2019              59.992441       63.909660  ...        NaN   
Apr 2019 to Mar 2020              66.805158       69.891601  ...        NaN   
Apr 2020 to Mar 2021              80.342981       85.562271  ...        NaN   
Apr 2021 to Mar 2022              70.824561       85.828677  ...  57.700000   
Apr 2022 to Mar 2023              63.629272       81.712892  ...  55.611672   

                      Merseyrail  Northern Trains   ScotRail  \
Time period                                                    
Apr 2017 to Mar 2018   64.600000        59.200000  62.900000   
Apr 2018 to Mar 2019   68.985986        53.502304  62.580408   
Apr 2019 to Mar 2020   72.606290        55.202322  66.353893   
Apr 2020 to Mar 2021   85.293760        76.308178  77.700265   
Apr 2021 to Mar 2022   78.856267        67.101111  71.204980   
Apr 2022 to Mar 2023   73.776278        60.094009  69.278388   

                      South Western Railway  Southeastern   TfW Rail  \
Time period                                                            
Apr 2017 to Mar 2018              63.000000     66.400000  63.700000   
Apr 2018 to Mar 2019              59.922957     67.189988  62.739755   
Apr 2019 to Mar 2020              59.896419     69.067480  60.511070   
Apr 2020 to Mar 2021              82.190871     78.268968  80.689091   
Apr 2021 to Mar 2022              74.641995     71.444707  67.058973   
Apr 2022 to Mar 2023              67.787431     65.286777  59.752507   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018             46.500000             60.900000   
Apr 2018 to Mar 2019             37.040217             59.155027   
Apr 2019 to Mar 2020             41.008346             52.836952   
Apr 2020 to Mar 2021             70.843382             74.363339   
Apr 2021 to Mar 2022             62.972224             66.288873   
Apr 2022 to Mar 2023             52.234307             58.518056   


In [ ]:
on_time.shape

(6, 24)

In [ ]:
on_time.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
on_time.describe()

Avanti West Coast        c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000   6.000000            6.000000           6.000000   
mean           48.560173  82.456565           67.617023          71.766927   
std             8.253061   2.422014            4.119104           4.833305   
min            39.558502  77.848792           61.654784          67.163523   
25%            42.254380  82.496842           66.265969          68.535725   
50%            48.128832  83.003054           67.719262          70.339818   
75%            52.128462  83.494642           68.276430          73.572819   
max            61.786970  84.897879           74.365140          80.173556   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean      53.131952              60.569044                 70.748574   
std        9.490279               7.491028                  6.416208   
min       45.612256              53.805982                 61.100000   
25%       46.772944              57.636204                 68.585494   
50%       48.610422              58.103904                 69.985513   
75%       57.596230              60.084108                 73.910048   
max       69.206661              75.175995                 80.083372   

       Grand Central  Great Western Railway  Greater Anglia  ...       Lumo  \
count       6.000000               6.000000        6.000000  ...   2.000000   
mean       53.789447              66.532402       75.117517  ...  56.655836   
std         8.235500               8.248832       10.472184  ...   1.476671   
min        47.021357              57.600000       63.800000  ...  55.611672   
25%        49.431550              60.901649       65.405145  ...  56.133754   
50%        50.288602              65.217215       75.802247  ...  56.655836   
75%        55.077392              69.819710       84.599926  ...  57.177918   
max        69.318600              80.342981       85.828677  ...  57.700000   

       Merseyrail  Northern Trains   ScotRail  South Western Railway  \
count    6.000000         6.000000   6.000000               6.000000   
mean    74.019764        61.901321  68.336322              67.906612   
std      7.302367         8.492101   5.716892               8.959871   
min     64.600000        53.502304  62.580408              59.896419   
25%     69.891062        56.201741  63.763473              60.692218   
50%     73.191284        59.647004  67.816140              65.393715   
75%     77.586270        65.349335  70.723332              72.928354   
max     85.293760        76.308178  77.700265              82.190871   

       Southeastern   TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000   6.000000              6.000000              6.000000   
mean      69.609653  65.741899             51.766413             62.010375   
std        4.764221   7.766207             13.038802              7.438215   
min       65.286777  59.752507             37.040217             52.836952   
25%       66.597497  61.068241             42.381260             58.677299   
50%       68.128734  63.219877             49.367154             60.027513   
75%       70.850401  66.219230             60.287745             64.941655   
max       78.268968  80.689091             70.843382             74.363339   

       Elizabeth line  
count        6.000000  
mean        80.168027  
std          7.740200  
min         68.000000  
25%         76.344909  
50%         81.229860  
75%         85.665701  
max         88.687536  

[8 rows x 24 columns]

In [ ]:
on_time[on_time.isin([on_time.max().max()])].stack()

Time period                           
Apr 2020 to Mar 2021  Heathrow Express    88.984919
dtype: float64

In [ ]:
on_time[on_time.isin([on_time.min().min()])].stack()

Time period                      
Apr 2018 to Mar 2019  Hull Trains    35.068036
dtype: float64

Heathrow Express had the highest on time percentage score with 89 during April 2020 to March 2021. Hull Trains had the lowest with 35.1.

In [ ]:
total_on_time = on_time.mean(axis=1)

In [ ]:
total_on_time[total_on_time.isin([total_on_time.max().max()])]

Time period
Apr 2020 to Mar 2021    77.534456
dtype: float64

In [ ]:
total_on_time[total_on_time.isin([total_on_time.min().min()])]

Time period
Apr 2018 to Mar 2019    60.055947
dtype: float64

Trains were most punctual during April 2020 to March 2021. They were least punctual during April 2018 to March 2019

## Network Rail on TOC delays (minutes)

In [ ]:
delays_nr_on_toc = data_tables["Network Rail on TOC delays (minutes)"]
delays_nr_on_toc

Avanti West Coast           c2c  Caledonian Sleeper  \
Time period                                                                 
Apr 2017 to Mar 2018      419092.575999  32167.799999        19733.539999   
Apr 2018 to Mar 2019      452629.298997  46091.219999        14379.309999   
Apr 2019 to Mar 2020      541889.580351  55804.048998        16470.795992   
Apr 2020 to Mar 2021      268997.462777  45028.448992         9013.638993   
Apr 2021 to Mar 2022      299663.721677  39440.716968        15635.071997   
Apr 2022 to Mar 2023      390900.137601  61043.422985        18476.916992   

                      Chiltern Railways   CrossCountry  East Midlands Railway  \
Time period                                                                     
Apr 2017 to Mar 2018      120561.769996  445243.513989          271596.805982   
Apr 2018 to Mar 2019      156460.066985  561757.063968          337561.581988   
Apr 2019 to Mar 2020      139075.172994  551665.778842          318359.473440   
Apr 2020 to Mar 2021       72663.989981  203674.252868          173823.607930   
Apr 2021 to Mar 2022       94824.958993  286552.530899          293043.872879   
Apr 2022 to Mar 2023      111647.055989  349656.166337          367115.815431   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018              1.493328e+06   27453.817992   
Apr 2018 to Mar 2019              1.380005e+06   32840.000000   
Apr 2019 to Mar 2020              1.487273e+06   33308.942996   
Apr 2020 to Mar 2021              8.264877e+05    5905.676995   
Apr 2021 to Mar 2022              9.320866e+05   26406.591990   
Apr 2022 to Mar 2023              1.321400e+06   37432.386987   

                      Great Western Railway  Greater Anglia  ...  \
Time period                                                  ...   
Apr 2017 to Mar 2018          843842.232959   462844.882996  ...   
Apr 2018 to Mar 2019          899263.331921   495870.045998  ...   
Apr 2019 to Mar 2020          702662.461911   449848.713386  ...   
Apr 2020 to Mar 2021          312722.874922   247679.189352  ...   
Apr 2021 to Mar 2022          662053.010874   232822.619962  ...   
Apr 2022 to Mar 2023          968737.251869   357216.367922  ...   

                              Lumo    Merseyrail  Northern Trains  \
Time period                                                         
Apr 2017 to Mar 2018           NaN  68428.499994     9.040530e+05   
Apr 2018 to Mar 2019           NaN  62531.525995     1.264744e+06   
Apr 2019 to Mar 2020           NaN  39420.919995     1.214946e+06   
Apr 2020 to Mar 2021           NaN  25622.974990     4.442857e+05   
Apr 2021 to Mar 2022   6570.500000  34060.758987     7.272081e+05   
Apr 2022 to Mar 2023  26293.579988  52149.537989     8.064813e+05   

                           ScotRail  South Western Railway   Southeastern  \
Time period                                                                 
Apr 2017 to Mar 2018  591526.939998           9.620135e+05  729796.686974   
Apr 2018 to Mar 2019  661105.222998           1.027658e+06  791793.418964   
Apr 2019 to Mar 2020  584789.566454           9.906494e+05  694253.747474   
Apr 2020 to Mar 2021  333477.938948           3.060947e+05  356984.588036   
Apr 2021 to Mar 2022  410941.834830           5.388129e+05  463292.752456   
Apr 2022 to Mar 2023  483533.003868           7.143984e+05  673904.327952   

                           TfW Rail  TransPennine Express  \
Time period                                                 
Apr 2017 to Mar 2018  300320.672000         284521.757990   
Apr 2018 to Mar 2019  286546.250994         427136.610994   
Apr 2019 to Mar 2020  370140.441395         394934.271406   
Apr 2020 to Mar 2021  193510.972898         124143.024942   
Apr 2021 to Mar 2022  344898.734705         174004.946908   
Apr 2022 to Mar 2023  419969.839600         189499.098845   

                      West Midl

In [ ]:
delays_nr_on_toc.shape

(6, 24)

In [ ]:
delays_nr_on_toc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
delays_nr_on_toc.describe()

Avanti West Coast           c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000      6.000000            6.000000           6.000000   
mean       395528.796234  46595.942990        15618.212329      115872.169156   
std        100457.865403  10541.340017         3768.038356       30118.209037   
min        268997.462777  32167.799999         9013.638993       72663.989981   
25%        322472.825658  40837.649974        14693.250498       99030.483242   
50%        404996.356800  45559.834495        16052.933994      116104.412993   
75%        444245.118247  53375.841748        17975.386742      134446.822244   
max        541889.580351  61043.422985        19733.539999      156460.066985   

        CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count       6.000000               6.000000              6.000000e+00   
mean   399758.217817          293583.526275              1.240097e+06   
std    145026.280268           67499.717966              2.889117e+05   
min    203674.252868          173823.607930              8.264877e+05   
25%    302328.439759          276958.572706              1.029415e+06   
50%    397449.840163          305701.673160              1.350703e+06   
75%    525060.212629          332761.054851              1.460456e+06   
max    561757.063968          367115.815431              1.493328e+06   

       Grand Central  Great Western Railway  Greater Anglia  ...  \
count       6.000000               6.000000        6.000000  ...   
mean    27224.569493          731546.860743   374380.303269  ...   
std     11206.864130          235828.574067   113725.609278  ...   
min      5905.676995          312722.874922   232822.619962  ...   
25%     26668.398490          672205.373633   275063.483994  ...   
50%     30146.908996          773252.347435   403532.540654  ...   
75%     33191.707247          885408.057181   459595.840594  ...   
max     37432.386987          968737.251869   495870.045998  ...   

               Lumo    Merseyrail  Northern Trains       ScotRail  \
count      2.000000      6.000000     6.000000e+00       6.000000   
mean   16432.039994  47035.702992     8.936197e+05  510895.751183   
std    13946.323605  16785.485486     3.092831e+05  123887.977949   
min     6570.500000  25622.974990     4.442857e+05  333477.938948   
25%    11501.269997  35400.799239     7.470264e+05  429089.627090   
50%    16432.039994  45785.228992     8.552671e+05  534161.285161   
75%    21362.809991  59936.028994     1.137223e+06  589842.596612   
max    26293.579988  68428.499994     1.264744e+06  661105.222998   

       South Western Railway   Southeastern       TfW Rail  \
count           6.000000e+00       6.000000       6.000000   
mean            7.566045e+05  618337.586976  319231.151932   
std             2.907279e+05  169531.869285   78269.197222   
min             3.060947e+05  356984.588036  193510.972898   
25%             5.827093e+05  515945.646330  289989.856246   
50%             8.382060e+05  684079.037713  322609.703352   
75%             9.834905e+05  720910.952099  363830.014722   
max             1.027658e+06  791793.418964  419969.839600   

       TransPennine Express  West Midlands Trains  Elizabeth line  
count              6.000000              6.000000        6.000000  
mean          265706.618514         454150.883027    60512.280315  
std           124394.912976         132397.930359    21427.921392  
min           124143.024942         256633.872330    35224.624968  
25%           177878.484892         404855.382121    53060.251738  
50%           237010.428417         462277.104991    54719.888994  
75%           367331.143052         488808.417773    63724.705227  
max           427136.610994         660350.219317    99175.928979  

[8 rows x 24 columns]

In [ ]:
delays_nr_on_toc[delays_nr_on_toc.isin([delays_nr_on_toc.max().max()])].stack()

Time period                                   
Apr 2017 to Mar 2018  Govia Thameslink Railway    1.493328e+06
dtype: float64

In [ ]:
delays_nr_on_toc[delays_nr_on_toc.isin([delays_nr_on_toc.min().min()])].stack()

Time period                      
Apr 2020 to Mar 2021  Hull Trains    1647.5
dtype: float64

Govia Thames Railway had 1.5 million minutes of delays caused to it by Network Rail. This was observed from April 2017 to March 2018
.

This is in contrast with Hull Trains with 1647.5 minutes from April 2020 to March 2021.

In [ ]:
total_delays_nr_on_toc = delays_nr_on_toc.sum(axis=1)

In [ ]:
total_delays_nr_on_toc[total_delays_nr_on_toc.isin([total_delays_nr_on_toc.max().max()])]

Time period
Apr 2018 to Mar 2019    9.889861e+06
dtype: float64

In [ ]:
total_delays_nr_on_toc[total_delays_nr_on_toc.isin([total_delays_nr_on_toc.min().min()])]

Time period
Apr 2020 to Mar 2021    4.445967e+06
dtype: float64

Delays caused by Network Rail onto the TOC was at its greatest country-wide between April 2018 to Mar 2019 (9.9 million minutes). It was at its lowest between April 2020 to March 2021.

##TOC on self delays (minutes)

Delay minutes occuring from the train operating company to itself.

In [ ]:
delays_toc_on_self = data_tables["TOC on self delays (minutes)"]
delays_toc_on_self

Avanti West Coast           c2c  Caledonian Sleeper  \
Time period                                                                 
Apr 2017 to Mar 2018      101071.500000  28426.199998        18341.460000   
Apr 2018 to Mar 2019       92535.579999  26893.279999        15962.689999   
Apr 2019 to Mar 2020      114736.496992  23546.769999        30565.559998   
Apr 2020 to Mar 2021       45289.129967  15273.968000         6452.258999   
Apr 2021 to Mar 2022       87410.256963  14230.191995        17845.000000   
Apr 2022 to Mar 2023      183870.706906  22652.612996        14751.081998   

                      Chiltern Railways  CrossCountry  East Midlands Railway  \
Time period                                                                    
Apr 2017 to Mar 2018      106168.729997  79533.283999           91084.250000   
Apr 2018 to Mar 2019       81857.143990  85107.430000          116814.500000   
Apr 2019 to Mar 2020       92217.300000  91639.000000          116823.500000   
Apr 2020 to Mar 2021       39981.983995  28055.792998           55566.365994   
Apr 2021 to Mar 2022       45361.407996  58988.018997          149867.873986   
Apr 2022 to Mar 2023       58153.447998  78859.598996          162153.986995   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018             849991.377326    7192.500000   
Apr 2018 to Mar 2019             882076.203484    9324.000000   
Apr 2019 to Mar 2020             662752.305491    8705.000000   
Apr 2020 to Mar 2021             308545.934879    1185.134999   
Apr 2021 to Mar 2022             480962.016481    5874.959999   
Apr 2022 to Mar 2023             564242.424985   10191.196000   

                      Great Western Railway  Greater Anglia  ...         Lumo  \
Time period                                                  ...                
Apr 2017 to Mar 2018          466831.539999   201441.100000  ...          NaN   
Apr 2018 to Mar 2019          485146.752995   209575.500000  ...          NaN   
Apr 2019 to Mar 2020          347809.924996   208384.069485  ...          NaN   
Apr 2020 to Mar 2021          129277.241996    83895.386492  ...          NaN   
Apr 2021 to Mar 2022          256867.606989    84458.800995  ...   837.500000   
Apr 2022 to Mar 2023          333509.137994    78626.376992  ...  6678.763998   

                        Merseyrail  Northern Trains       ScotRail  \
Time period                                                          
Apr 2017 to Mar 2018  45508.499992     5.827176e+05  306146.000000   
Apr 2018 to Mar 2019  44949.139997     8.941070e+05  369358.399999   
Apr 2019 to Mar 2020  32095.299995     1.111259e+06  358546.800000   
Apr 2020 to Mar 2021  10364.024998     2.984220e+05  154866.580992   
Apr 2021 to Mar 2022  20227.692999     5.727465e+05  241688.839978   
Apr 2022 to Mar 2023  35740.091999     6.908461e+05  275963.290979   

                      South Western Railway   Southeastern       TfW Rail  \
Time period                                                                 
Apr 2017 to Mar 2018          384015.000000  312556.699992  194552.000000   
Apr 2018 to Mar 2019          400130.724000  344441.415998  236051.000000   
Apr 2019 to Mar 2020          432463.738999  268488.349998  325870.242997   
Apr 2020 to Mar 2021          114911.140997  134868.557397  102260.053993   
Apr 2021 to Mar 2022          169935.898000  190370.336998  255703.803473   
Apr 2022 to Mar 2023          201535.691500  274252.748998  410452.639947   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018          72375.580000         217753.699999   
Apr 2018 to Mar 2019         138685.888999         205955.819997   
Apr 2019 to Mar 2020         181844.680495         404775.286471   
Apr 2020 to Mar 2021          45171.168998         118563.463474   
Apr 2021

In [ ]:
delays_toc_on_self.shape

(6, 24)

In [ ]:
delays_toc_on_self.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
delays_toc_on_self.describe()

Avanti West Coast           c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000      6.000000            6.000000           6.000000   
mean       104152.278471  21837.170498        17319.675166       70623.335663   
std         45511.884007   5890.823014         7788.623616       26790.029203   
min         45289.129967  14230.191995         6452.258999       39981.983995   
25%         88691.587722  17118.629249        15053.983998       48559.417997   
50%         96803.540000  23099.691497        16903.845000       70005.295994   
75%        111320.247744  26056.652499        18217.345000       89627.260998   
max        183870.706906  28426.199998        30565.559998      106168.729997   

       CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count      6.000000               6.000000                  6.000000   
mean   70363.854165          115385.079496             624761.710441   
std    23433.491622           38856.955414             220325.118449   
min    28055.792998           55566.365994             308545.934879   
25%    63955.913997           97516.812500             501782.118607   
50%    79196.441497          116819.000000             613497.365238   
75%    83713.893500          141606.780490             803181.609367   
max    91639.000000          162153.986995             882076.203484   

       Grand Central  Great Western Railway  Greater Anglia  ...         Lumo  \
count       6.000000               6.000000        6.000000  ...     2.000000   
mean     7078.798500          336573.700828   144396.872327  ...  3758.131999   
std      3273.221774          133042.537569    68081.449832  ...  4130.397384   
min      1185.134999          129277.241996    78626.376992  ...   837.500000   
25%      6204.344999          276027.989740    84036.240118  ...  2297.815999   
50%      7948.750000          340659.531495   142949.950498  ...  3758.131999   
75%      9169.250000          437076.136248   206648.327114  ...  5218.447998   
max     10191.196000          485146.752995   209575.500000  ...  6678.763998   

         Merseyrail  Northern Trains       ScotRail  South Western Railway  \
count      6.000000     6.000000e+00       6.000000               6.000000   
mean   31480.791663     6.916830e+05  284428.318658          283832.032249   
std    13922.947472     2.820260e+05   79828.427611          137063.986211   
min    10364.024998     2.984220e+05  154866.580992          114911.140997   
25%    23194.594748     5.752393e+05  250257.452728          177835.846375   
50%    33917.695997     6.367818e+05  291054.645490          292775.345750   
75%    42646.877997     8.432918e+05  345446.600000          396101.793000   
max    45508.499992     1.111259e+06  369358.399999          432463.738999   

        Southeastern       TfW Rail  TransPennine Express  \
count       6.000000       6.000000              6.000000   
mean   254163.018230  254148.290068         105642.931080   
std     78063.433373  106326.641911          51502.902489   
min    134868.557397  102260.053993          45171.168998   
25%    209899.840248  204926.750000          71106.265747   
50%    271370.549498  245877.401737          98736.343496   
75%    302980.712243  308328.633116         135288.693497   
max    344441.415998  410452.639947         181844.680495   

       West Midlands Trains  Elizabeth line  
count              6.000000        6.000000  
mean          240218.778402    31632.850832  
std            94307.310159    11969.278561  
min           118563.463474    21802.500000  
25%           208905.289998    23580.051999  
50%           222341.818496    26064.478999  
75%           257233.331856    38355.487496  
max           404775.286471    50661.247000  

[8 rows x 24 columns]

In [ ]:
delays_toc_on_self[delays_toc_on_self.isin([delays_toc_on_self.max().max()])].stack()


Time period                          
Apr 2019 to Mar 2020  Northern Trains    1.111259e+06
dtype: float64

In [ ]:
delays_toc_on_self[delays_toc_on_self.isin([delays_toc_on_self.min().min()])].stack()

Time period                      
Apr 2020 to Mar 2021  Hull Trains    192.0
dtype: float64

The company who had caused the most minutes of delays to themselves in a year was Northern Trains, with 1.1 million minutes of delays, occurring between April 2019 to March 2020.

The company who had the least was Hull Trains with 192 minutes during April 2020 to March 2021.

In [ ]:
total_delays_toc_on_self = delays_toc_on_self.sum(axis=1)

In [ ]:
total_delays_toc_on_self[total_delays_toc_on_self.isin([total_delays_toc_on_self.max().max()])]

Time period
Apr 2019 to Mar 2020    5.039943e+06
dtype: float64

In [ ]:
total_delays_toc_on_self[total_delays_toc_on_self.isin([total_delays_toc_on_self.min().min()])]

Time period
Apr 2020 to Mar 2021    1.796804e+06
dtype: float64

Total delays of TOC on self was at its highest during April 2019 to March 2020, with a total of 5 million minutes.

The lowest was at April 2020 to March 2021 with 1.8 million minutes.

## TOC on TOC delays (minutes)

In [ ]:
delays_toc_on_toc = data_tables["TOC on TOC delays (minutes)"]
delays_toc_on_toc

Avanti West Coast          c2c  Caledonian Sleeper  \
Time period                                                                
Apr 2017 to Mar 2018       93677.423999  2491.000000         4018.000000   
Apr 2018 to Mar 2019      103164.120996  1953.500000         3787.000000   
Apr 2019 to Mar 2020      156004.922465  2889.181000         5345.644000   
Apr 2020 to Mar 2021       42218.406986  1513.582999         1943.102000   
Apr 2021 to Mar 2022       72766.020970  3184.090998         2751.927999   
Apr 2022 to Mar 2023       98002.154964  3159.964000         6849.000999   

                      Chiltern Railways   CrossCountry  East Midlands Railway  \
Time period                                                                     
Apr 2017 to Mar 2018       37030.500000  196433.201998           81135.944000   
Apr 2018 to Mar 2019       29150.788996  225569.505995           95651.917998   
Apr 2019 to Mar 2020       38735.526995  250747.220955          110049.026480   
Apr 2020 to Mar 2021        7742.025997   42973.953974           30388.025986   
Apr 2021 to Mar 2022       15053.132999   83977.949970           60831.252982   
Apr 2022 to Mar 2023       15426.495997  113591.234429           78553.197480   

                      Govia Thameslink Railway  Grand Central  \
Time period                                                     
Apr 2017 to Mar 2018             106204.500000   13592.681998   
Apr 2018 to Mar 2019             128195.432997   18484.000000   
Apr 2019 to Mar 2020             141727.408475   15299.056996   
Apr 2020 to Mar 2021              51763.407494    1293.188000   
Apr 2021 to Mar 2022              68729.426985    7216.447997   
Apr 2022 to Mar 2023             100544.162987   11169.416995   

                      Great Western Railway  Greater Anglia  ...         Lumo  \
Time period                                                  ...                
Apr 2017 to Mar 2018          147505.226992    80495.017000  ...          NaN   
Apr 2018 to Mar 2019          145402.914996    83478.953999  ...          NaN   
Apr 2019 to Mar 2020          148318.612989    69692.216994  ...          NaN   
Apr 2020 to Mar 2021           48518.382981    27515.423993  ...          NaN   
Apr 2021 to Mar 2022           97961.881976    32078.578994  ...  1814.500000   
Apr 2022 to Mar 2023          126500.609969    41009.254992  ...  8170.155998   

                       Merseyrail  Northern Trains       ScotRail  \
Time period                                                         
Apr 2017 to Mar 2018  2770.000000    204870.973997   80594.060000   
Apr 2018 to Mar 2019  2025.334000    312481.062999   95074.377000   
Apr 2019 to Mar 2020  1478.779999    358614.360973  113497.633486   
Apr 2020 to Mar 2021   249.000000     64211.305980   15357.479988   
Apr 2021 to Mar 2022   664.547999    137899.416458   28902.324983   
Apr 2022 to Mar 2023  1394.369999    197018.596421   46691.704966   

                      South Western Railway  Southeastern      TfW Rail  \
Time period                                                               
Apr 2017 to Mar 2018           61766.450495  30843.612996  61413.327999   
Apr 2018 to Mar 2019           58413.562996  41316.164997  70063.748998   
Apr 2019 to Mar 2020           51409.812995  44188.902493  86108.315474   
Apr 2020 to Mar 2021           13746.175998  23713.854493  19266.972982   
Apr 2021 to Mar 2022           29555.159991  22353.910490  38054.961477   
Apr 2022 to Mar 2023           45976.926995  32404.922991  62837.519960   

                      TransPennine Express  West Midlands Trains  \
Time period                                                        
Apr 2017 to Mar 2018         129657.661999         123062.988000   
Apr 2018 to Mar 2019         204329.000000         120383.781997   
Apr 2019 to Mar 2020         221474.047986         159953.493984   
Apr 2020 to Mar 2021          31939.805994          34521.663983   
Apr 2021 to Mar 2022          63

In [ ]:
delays_toc_on_toc.shape

(6, 24)

In [ ]:
delays_toc_on_toc.info()

<class 'pandas.core.frame.DataFrame'>
Index: 6 entries, Apr 2017 to Mar 2018 to Apr 2022 to Mar 2023
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype  
---  ------                        --------------  -----  
 0   Avanti West Coast             6 non-null      float64
 1   c2c                           6 non-null      float64
 2   Caledonian Sleeper            6 non-null      float64
 3   Chiltern Railways             6 non-null      float64
 4   CrossCountry                  6 non-null      float64
 5   East Midlands Railway         6 non-null      float64
 6   Govia Thameslink Railway      6 non-null      float64
 7   Grand Central                 6 non-null      float64
 8   Great Western Railway         6 non-null      float64
 9   Greater Anglia                6 non-null      float64
 10  Heathrow Express              6 non-null      float64
 11  Hull Trains                   6 non-null      float64
 12  London North Eastern Railway  6 non

In [ ]:
delays_toc_on_toc.describe()

Avanti West Coast          c2c  Caledonian Sleeper  Chiltern Railways  \
count           6.000000     6.000000            6.000000           6.000000   
mean        94305.508397  2531.886499         4115.779166       23856.411831   
std         37620.122412   681.271764         1770.951252       12893.484608   
min         42218.406986  1513.582999         1943.102000        7742.025997   
25%         77993.871727  2087.875000         3010.695999       15146.473749   
50%         95839.789482  2690.090500         3902.500000       22288.642497   
75%        101873.629488  3092.268250         5013.733000       35060.572249   
max        156004.922465  3184.090998         6849.000999       38735.526995   

        CrossCountry  East Midlands Railway  Govia Thameslink Railway  \
count       6.000000               6.000000                  6.000000   
mean   152215.511220           76101.560821              99527.389823   
std     83816.976685           27888.750403              34287.689991   
min     42973.953974           30388.025986              51763.407494   
25%     91381.271085           65261.739106              76683.110985   
50%    155012.218213           79844.570740             103374.331493   
75%    218285.429996           92022.924499             122697.699748   
max    250747.220955          110049.026480             141727.408475   

       Grand Central  Great Western Railway  Greater Anglia  ...         Lumo  \
count       6.000000               6.000000        6.000000  ...     2.000000   
mean    11175.798664          119034.604984    55711.574329  ...  4992.327999   
std      6157.838631           39587.259734    25101.411633  ...  4494.127455   
min      1293.188000           48518.382981    27515.423993  ...  1814.500000   
25%      8204.690247          105096.563974    34311.247994  ...  3403.414000   
50%     12381.049496          135951.762482    55350.735993  ...  4992.327999   
75%     14872.463246          146979.648993    77794.316998  ...  6581.241998   
max     18484.000000          148318.612989    83478.953999  ...  8170.155998   

        Merseyrail  Northern Trains       ScotRail  South Western Railway  \
count     6.000000         6.000000       6.000000               6.000000   
mean   1430.338666    212515.952805   63352.930070           43478.014912   
std     909.323775    108810.181185   38951.256408           18463.605224   
min     249.000000     64211.305980   15357.479988           13746.175998   
25%     847.003499    152679.211449   33349.669979           33660.601742   
50%    1436.574999    200944.785209   63642.882483           48693.369995   
75%    1888.695500    285578.540749   91454.297750           56662.625496   
max    2770.000000    358614.360973  113497.633486           61766.450495   

       Southeastern      TfW Rail  TransPennine Express  West Midlands Trains  \
count      6.000000      6.000000              6.000000              6.000000   
mean   32470.228077  56290.807815         120986.200319         105032.005057   
std     8913.383547  23879.647243          78070.250587          44043.307377   
min    22353.910490  19266.972982          31939.805994          34521.663983   
25%    25496.294119  43894.553107          66196.617471          85000.187575   
50%    31624.267993  62125.423980         102519.727980         119394.280208   
75%    39088.354495  68257.191738         185661.165500         122393.186499   
max    44188.902493  86108.315474         221474.047986         159953.493984   

       Elizabeth line  
count        6.000000  
mean     16838.785495  
std       4262.438908  
min       8896.416994  
25%      16383.477493  
50%      17608.946494  
75%      19539.422997  
max      20760.500000  

[8 rows x 24 columns]

In [ ]:
delays_toc_on_toc[delays_toc_on_toc.isin([delays_toc_on_toc.max().max()])].stack()

Time period                          
Apr 2019 to Mar 2020  Northern Trains    358614.360973
dtype: float64

In [ ]:
delays_toc_on_toc[delays_toc_on_toc.isin([delays_toc_on_toc.min().min()])].stack()

Time period                      
Apr 2020 to Mar 2021  Hull Trains    236.5
dtype: float64

The company who had experienced the most minutes of delays caused by other TOC's in a year was Northern Trains, with 358,614 minutes of delays, occurring between April 2019 to March 2020.

The company who had the least was Hull Trains with 236.5 minutes during April 2020 to March 2021.

In [ ]:
total_delays_toc_on_toc = delays_toc_on_toc.sum(axis=1)

In [ ]:
total_delays_toc_on_toc[total_delays_toc_on_toc.isin([total_delays_toc_on_toc.max().max()])]

Time period
Apr 2019 to Mar 2020    2.135845e+06
dtype: float64

In [ ]:
total_delays_toc_on_toc[total_delays_toc_on_toc.isin([total_delays_toc_on_toc.min().min()])]

Time period
Apr 2020 to Mar 2021    503194.261809
dtype: float64

Countrywide, the most delay minutes caused by TOCs on TOCs was in April 2019 to March 2020 with 2.14 million minutes.

# Data Visualisation

## FTE Employees

In [ ]:
full_time_employees_2023 = full_time_employees[full_time_employees.index == "As of 31 March 2023"]

In [ ]:
full_time_employees_2023_fig = px.bar(x=full_time_employees.columns,
                                      y=full_time_employees_2023.values[0],
                                      color=full_time_employees.columns,
                                      )
full_time_employees_2023_fig.update_layout(title="Number of FTE employees as of 31 March 2023",
                                           xaxis_title="Date",
                                           yaxis_title="Number of FTE employees",
                                           coloraxis_showscale=False,
                                           showlegend=False)
full_time_employees_2023_fig.show()

In [ ]:
total_full_time_employees_fig = px.line(x=total_full_time_employees.index, y=total_full_time_employees.values, markers=True)
total_full_time_employees_fig.update_layout(title="Country wide FTE employees",
                                            xaxis_title="Date",
                                            yaxis_title="Number of FTE employees")
total_full_time_employees_fig.show()

In [ ]:
fte_trends_figure = px.line(full_time_employees.reset_index(), x=full_time_employees.index, y=full_time_employees.columns, markers=True, height=650, width=750)
fte_trends_figure.update_layout(title="FTE Employees in each TOC over time",
                     xaxis_title="Number of FTE Employees",
                     yaxis_title="Date",
                     legend_title="TOC")
fte_trends_figure.show()

## Managed Stations

In [ ]:
total_managed_stations_figure = px.line(x=total_managed_stations.index, y=total_managed_stations.values, markers=True)
total_managed_stations_figure.update_layout(title="Total number of stations managed through the country",
                                            xaxis_title="Date",
                                            yaxis_title="Number of stations managed")
total_managed_stations_figure.show()

In [ ]:
managed_stations_2023 = managed_stations[managed_stations.index == "As of 31 March 2023"]
managed_stations_2023_pie = px.pie(values=managed_stations_2023.values[0], names=managed_stations_2023.columns, title="Managed stations in 2023")
managed_stations_2023_pie.show()

In [ ]:
managed_stations_trends_figure = px.line(managed_stations.reset_index(), x=managed_stations.index, y=managed_stations.columns, markers=True, height=650, width=750)
managed_stations_trends_figure.update_layout(title="Managed Stations in each TOC over time",
                     xaxis_title="Number of Managed Stations",
                     yaxis_title="Date",
                     legend_title="TOC",
                                             autosize=True)
managed_stations_trends_figure.show()

## Total Passenger Journeys

In [ ]:
total_journeys_figure =px.line(x=total_journeys.index, y=total_journeys.values, markers=True)
total_journeys_figure.update_layout(title="Total number of passenger journeys throughout the country",
                                            xaxis_title="Date",
                                            yaxis_title="Number of journeys (millions)")
total_journeys_figure.show()

In [ ]:
journeys_2023 = journeys[journeys.index == "Apr 2022 to Mar 2023"]
journeys_2023_pie = px.pie(values=journeys_2023.values[0], names=journeys_2023.columns, title="Passenger Journeys in 2023")
journeys_2023_pie.show()


In [ ]:
journeys_2023_bar = px.bar(x=journeys_2023.columns,
                           y=journeys_2023.values[0],
                           color=journeys_2023.columns)
journeys_2023_bar.update_layout(title="Passenger Journeys in 2023 by TOCs",
                                xaxis_title="TOC",
                                yaxis_title="Number of passenger journeys (millions)",
                                coloraxis_showscale=False,
                                showlegend=False)
journeys_2023_bar .show()

In [ ]:
journeys_trends_figure = px.line(journeys.reset_index(), x=journeys.index, y=journeys.columns, markers=True, height=660, width=750)
journeys_trends_figure.update_layout(title="Passenger journeys in each TOC over time",
                     xaxis_title="Number of passenger journeys (millions)",
                     yaxis_title="Time period",
                     legend_title="TOC")
journeys_trends_figure.show()


## Passenger km

In [ ]:
total_passenger_km_figure = px.line(x=total_passenger_km.index, y=total_passenger_km.values, markers=True)
total_passenger_km_figure.update_layout(title="Passenger km travelled throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Passenger km travelled (millions)")
total_passenger_km_figure.show()

passenger_km_trends_figure = px.line(passenger_km.reset_index(), x=passenger_km.index, y=passenger_km.columns, markers=True, height=660, width=750)
passenger_km_trends_figure.update_layout(title="Passenger km travelled by TOC",
                                        xaxis_title="Time period",
                                        yaxis_title="Passenger km travelled (millions)",
                                        legend_title="TOC")
passenger_km_trends_figure.show()

In [ ]:
passenger_km_2023 = passenger_km[passenger_km.index=="Apr 2022 to Mar 2023"]
passenger_km_2023_pie = px.pie(values=passenger_km_2023.values[0], names=passenger_km_2023.columns, title="Passenger km travelled in 2023")
passenger_km_2023_pie.show()

passenger_km_2023_bar = px.bar(x=passenger_km_2023.columns,
                             y=passenger_km_2023.values[0],
                             color=passenger_km_2023.columns)
passenger_km_2023_bar.update_layout(title="Passenger km travelled in 2023 by TOC ",
                                  xaxis_title="TOC",
                                  yaxis_title="Passenger km travelled (millions)",
                                  showlegend=False,
                                  coloraxis_showscale=False)
passenger_km_2023_bar.show()

## Passenger train km

In [ ]:
total_train_km_figure = px.line(x=total_train_km.index, y=total_train_km.values, markers=True)
total_train_km_figure.update_layout(title="Distance travelled by trains throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Train km travelled (millions)")
total_train_km_figure.show()

total_train_km_figure = px.line(train_km.reset_index(), x=train_km.index, y=train_km.columns, markers=True, height=660, width=750)
total_train_km_figure.update_layout(title="Distance travelled by trains by TOC",
                                    xaxis_title="Time period",
                                    yaxis_title="Train km travelled (millions)",
                                    legend_title="TOC")
total_train_km_figure.show()

In [ ]:
train_km_2023 = complaints[train_km.index=="Apr 2022 to Mar 2023"]
train_km_2023_pie = px.pie(values=train_km_2023.values[0], names=train_km_2023.columns, title="Distance travelled by trains in 2023")
train_km_2023_pie.show()

train_km_2023_bar = px.bar(x=train_km_2023.columns,
                             y=train_km_2023.values[0],
                             color=train_km_2023.columns)
train_km_2023_bar.update_layout(title="Distance travelled by trains in 2023 by TOCs",
                                  xaxis_title="TOC",
                                  yaxis_title="Distance travelled by trains (millions)",
                                  showlegend=False,
                                  coloraxis_showscale=False)
train_km_2023_bar.show()

## Route operated

In [ ]:
total_route_km_figure = px.line(x=total_route_km.index, y=total_route_km.values, markers=True)
total_route_km_figure.update_layout(title="Route kilometres operated throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Route operated (km)")
total_route_km_figure.show()

total_route_km_figure = px.line(route_km.reset_index(), x=route_km.index, y=route_km.columns, markers=True, height=650, width=750)
total_route_km_figure.update_layout(title="Route kilometres operated by TOC",
                                    xaxis_title="Time period",
                                    yaxis_title="Route operated (km)",
                                    legend_title="TOC")
total_route_km_figure.show()


In [ ]:
route_km_2023 = route_km[route_km.index=="As of 31 March 2023"]
route_km_2023_pie = px.pie(values=route_km_2023.values[0], names=route_km_2023.columns, title="Amount of train routes in operation in 2022 (millions of km)")
route_km_2023_pie.show()

route_km_2023_bar = px.bar(x=route_km_2023.columns,
                             y=route_km_2023.values[0],
                             color=route_km_2023.columns)
route_km_2023_bar.update_layout(title="Amount of train routes in operation in 2022 by TOCs",
                                  xaxis_title="TOC",
                                  yaxis_title="Route operated (millions of km)",
                                  showlegend=False,
                                  coloraxis_showscale=False)
route_km_2023_bar.show()



## Complaints Closed

In [ ]:
total_complaints_figure = px.line(x=total_complaints.index, y=total_complaints.values, markers=True)
total_complaints_figure.update_layout(title="Number of complaints closed throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of complaints closed")
total_complaints_figure.show()

complaints_trends_figure = px.line(complaints.reset_index(), x=complaints.index, y=complaints.columns, markers=True, height=660, width=750)
complaints_trends_figure.update_layout(title="Number of complaints closed",
                                       xaxis_title="Time period",
                                       yaxis_title="Number of complaints closed",
                                       legend_title="TOC")
complaints_trends_figure.show()

In [ ]:
complaints_2023 = complaints[complaints.index=="Apr 2022 to Mar 2023"]
complaints_2023_pie = px.pie(values=complaints_2023.values[0], names=complaints_2023.columns, title="Number of complaints closed in 2023")
complaints_2023_pie.show()

complaints_2023_bar = px.bar(x=complaints_2023.columns,
                             y=complaints_2023.values[0],
                             color=complaints_2023.columns)
complaints_2023_bar.update_layout(title="Number of complaints closed in 2023",
                                  xaxis_title="TOC",
                                  yaxis_title="Number of complaints closed",
                                  showlegend=False,
                                  coloraxis_showscale=False)
complaints_2023_bar.show()

## Total Assist Requests

In [ ]:
total_assists_figure = px.line(x=total_assists.index, y=total_assists.values, markers=True)
total_assists_figure.update_layout(title="Number of assistance requests made throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of assists made")
total_assists_figure.show()

assists_trends_figure = px.line(assists.reset_index(), x=assists.index, y=assists.columns, markers=True, height=660, width=750)
assists_trends_figure.update_layout(title="Number of assistance requests made",
                                    xaxis_title="Time period",
                                    yaxis_title="Number of assistance requests made",
                                    legend_title="TOC")
assists_trends_figure.show()

In [ ]:
assists_2023 = assists[assists.index=="Apr 2022 to Mar 2023"]
assists_2023_pie = px.pie(values=assists_2023.values[0], names=assists_2023.columns, title="Number of assists requests carried out in 2023")
assists_2023_pie.show()

assists_2023_bar = px.bar(x=assists_2023.columns,
                          y=assists_2023.values[0],
                          color=assists_2023.columns)
assists_2023_bar.update_layout(title="Number of assists requests carried out in 2023 by TOC",
                                  xaxis_title="TOC",
                                  yaxis_title="Number of assists requests carried out",
                                  showlegend=False,
                                  coloraxis_showscale=False)
assists_2023_bar.show()

## Delay compensation claims closed

In [ ]:
total_delay_compensations_figure = px.line(x=total_delay_compensations.index, y=total_delay_compensations.values, markers=True)
total_delay_compensations_figure.update_layout(title="Number of delay compensation claims closed throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of claims closed")
total_delay_compensations_figure.show()

delay_compensations_trends_figure = px.line(delay_compensations.reset_index(), x=delay_compensations.index, y=delay_compensations.columns, markers=True, height=660, width=750)
delay_compensations_trends_figure.update_layout(title="Number of delay compensation claims closed by TOC ",
                                                xaxis_title="Time period",
                                                yaxis_title="Number of claims closed",
                                                legend_title="TOC")
delay_compensations_trends_figure.show()

In [ ]:
delay_compensations_2023 = delay_compensations[delay_compensations.index=="Apr 2022 to Mar 2023"]
delay_compensations_2023_pie = px.pie(values=delay_compensations_2023.values[0], names=delay_compensations_2023.columns, title="Number of delay compensation claims closed in 2022")
delay_compensations_2023_pie.show()

delay_compensations_2023_bar = px.bar(x=delay_compensations_2023.columns,
                          y=delay_compensations_2023.values[0],
                          color=delay_compensations_2023.columns)
delay_compensations_2023_bar.update_layout(title="Number of delay compensation claims closed in 2023 by TOC",
                                  xaxis_title="TOC",
                                  yaxis_title="Number of delay compensation claims closed",
                                  showlegend=False,
                                  coloraxis_showscale=False)
delay_compensations_2023_bar.show()

## Cancellations score

Cancellation score - This measure is a weighted score which counts full cancellations as one and part cancellations as half

In [ ]:
total_cancellation_score_figure = px.line(x=total_cancellation_score.index, y=total_cancellation_score.values, markers=True)
total_cancellation_score_figure.update_layout(title="Mean cancellation scores (percentage) throughout the country over time",
                                      xaxis_title="Time period",
                                      yaxis_title="Mean cancellation score")
total_cancellation_score_figure.show()

cancellation_score_trends_figure = px.line(cancellation_score.reset_index(), x=cancellation_score.index, y=cancellation_score.columns, markers=True, height=660, width=750)
cancellation_score_trends_figure.update_layout(title="Cancellation scores by TOC",
                                               xaxis_title="Time period",
                                               yaxis_title="Cancellation score",
                                               legend_title="TOC")
cancellation_score_trends_figure.show()

In [ ]:
cancellation_score_2023 = cancellation_score[cancellation_score.index == "Apr 2022 to Mar 2023"]
cancellation_score_2023_bar = px.bar(x=cancellation_score_2023.columns,
                          y=cancellation_score_2023.values[0],
                          color=cancellation_score_2023.columns)
cancellation_score_2023_bar.update_layout(title="Cancellation score in 2023 by TOC",
                                  xaxis_title="TOC",
                                  yaxis_title="Cancellation score",
                                  showlegend=False,
                                  coloraxis_showscale=False)
cancellation_score_2023_bar.show()

## Trains planned

In [ ]:
total_trains_planned_figure = px.line(x=total_trains_planned.index, y=total_trains_planned.values, markers=True)
total_trains_planned_figure.update_layout(title="Number of trains planned throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of trains planned")
total_trains_planned_figure.show()

trains_planned_trends_figure = px.line(trains_planned.reset_index(), x=trains_planned.index, y=trains_planned.columns, markers=True, height=660, width=750)
trains_planned_trends_figure.update_layout(title="Number of trains planned by TOC ",
                                           xaxis_title="Time period",
                                           yaxis_title="Number of trains planned",
                                           legend_title="TOC")
trains_planned_trends_figure.show()

In [ ]:
trains_planned_2023 = trains_planned[trains_planned.index=="Apr 2022 to Mar 2023"]
trains_planned_2023_pie = px.pie(values=trains_planned_2023.values[0], names=trains_planned_2023.columns, title="Number of trains planned in 2023")
trains_planned_2023_pie.show()

trains_planned_2023_bar = px.bar(x=trains_planned_2023.columns,
                          y=trains_planned_2023.values[0],
                          color=trains_planned_2023.columns)
trains_planned_2023_bar.update_layout(title="Number trains planned in 2023 by TOC",
                                  xaxis_title="TOC",
                                  yaxis_title="Number of trains planned",
                                  showlegend=False,
                                  coloraxis_showscale=False)
trains_planned_2023_bar.show()

## On Time trains

In [ ]:
total_on_time_figure = px.line(x=total_on_time.index, y=total_on_time.values, markers=True)
total_on_time_figure.update_layout(title="On Time trains throughout the country",
                                      xaxis_title="Time period",
                                      yaxis_title="Percentage of on time trains")
total_on_time_figure.show()

on_time_trends_figure = px.line(on_time.reset_index(), x=on_time.index, y=on_time.columns, markers=True, height=660, width=750)
on_time_trends_figure.update_layout(title="On time trains by TOC ",
                                    xaxis_title="Time period",
                                    yaxis_title="Percentage of on time trains",
                                    legend_title="TOC")
on_time_trends_figure.show()

In [ ]:
on_time_2023 = on_time[on_time.index=="Apr 2022 to Mar 2023"]
on_time_2023_bar = px.bar(x=on_time.columns,
                          y=on_time_2023.values[0],
                          color=on_time.columns)
on_time_2023_bar.update_layout(title="On Time Trains in 2023",
                                  xaxis_title="TOC",
                                  yaxis_title="Percentage of trains on time",
                                  showlegend=False,
                                  coloraxis_showscale=False)
on_time_2023_bar.show()

## Network Rail on TOC delays (minutes)

In [ ]:
total_delays_nr_on_toc_figure = px.line(x=total_delays_nr_on_toc.index, y=total_delays_nr_on_toc.values, markers=True)
total_delays_nr_on_toc_figure.update_layout(title="Delay minutes caused by NR onto the Country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of delay minutes caused by NR")
total_delays_nr_on_toc_figure.show()

delays_nr_on_toc_trends_figure = px.line(delays_nr_on_toc.reset_index(), x=delays_nr_on_toc.index, y=delays_nr_on_toc.columns, markers=True, height=660, width=750)
delays_nr_on_toc_trends_figure.update_layout(title="Delay minutes caused by NR onto each TOC ",
                                             xaxis_title="Time period",
                                             yaxis_title="Number of delay minutes caused by NR",
                                             legend_title="TOC")
delays_nr_on_toc_trends_figure.show()

In [ ]:
delays_nr_on_toc_2023 = delays_nr_on_toc[delays_nr_on_toc.index=="Apr 2022 to Mar 2023"]
delays_nr_on_toc_2023_pie = px.pie(values=delays_nr_on_toc_2023.values[0], names=delays_nr_on_toc_2023.columns, title="Number of delay minutes caused by NR in 2023")
delays_nr_on_toc_2023_pie.show()

delays_nr_on_toc_2023_bar = px.bar(x=delays_nr_on_toc.columns,
                          y=delays_nr_on_toc_2023.values[0],
                          color=delays_nr_on_toc_2023.columns)
delays_nr_on_toc_2023_bar.update_layout(title="Number of delay minutes caused by NR in 2023 by TOC",
                                  xaxis_title="TOC",
                                  yaxis_title="Number of delay minutes caused by NR",
                                  showlegend=False,
                                  coloraxis_showscale=False)
delays_nr_on_toc_2023_bar.show()

##TOC on self delays (minutes)

In [ ]:
total_delays_toc_on_self_figure = px.line(x=total_delays_toc_on_self.index, y=total_delays_toc_on_self.values, markers=True)
total_delays_toc_on_self_figure.update_layout(title="Self-inflicted delay minutes created across the Country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of delay minutes")
total_delays_toc_on_self_figure.show()

delays_toc_on_self_trends_figure = px.line(delays_toc_on_self.reset_index(), x=delays_toc_on_self.index, y=delays_toc_on_self.columns, markers=True, height=660, width=750)
delays_toc_on_self_trends_figure.update_layout(title=" Self-inflicted delay minutes by each TOC ",
                                               xaxis_title="Time period",
                                               yaxis_title="Number of delay minutes",
                                               legend_title="TOC")
delays_toc_on_self_trends_figure.show()


In [ ]:
delays_toc_on_self_2023 = delays_toc_on_self[delays_toc_on_self.index=="Apr 2022 to Mar 2023"]
delays_toc_on_self_2023_pie = px.pie(values=delays_toc_on_self_2023.values[0], names=delays_toc_on_self_2023.columns, title="Number of self-inflicted in 2023")
delays_toc_on_self_2023_pie.show()

delays_toc_on_self_2023_bar = px.bar(x=delays_toc_on_self.columns,
                          y=delays_toc_on_self_2023.values[0],
                          color=delays_toc_on_self_2023.columns)
delays_toc_on_self_2023_bar.update_layout(title="Number of self-inflicted delay minutes in 2023",
                                  xaxis_title="TOC",
                                  yaxis_title="Number of delay minutess caused",
                                  showlegend=False,
                                  coloraxis_showscale=False)
delays_toc_on_self_2023_bar.show()



## TOC on TOC delays (minutes)

In [ ]:
total_delays_toc_on_toc_figure = px.line(x=total_delays_toc_on_toc.index, y=total_delays_toc_on_toc.values, markers=True)
total_delays_toc_on_toc_figure.update_layout(title="Number of delay minutes caused by TOCs to TOCs across the Country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of delay minutes")
total_delays_toc_on_toc_figure.show()

delays_toc_on_toc_trends_figure = px.line(delays_toc_on_toc.reset_index(), x=delays_toc_on_toc.index, y=delays_toc_on_toc.columns, markers=True, height=660, width=750)
delays_toc_on_toc_trends_figure.update_layout(title="Number of delay minutes caused by TOCs to TOCs ",
                                              xaxis_title="Time period",
                                              yaxis_title="Number of delay minutes",
                                              legend_title="TOC")
delays_toc_on_toc_trends_figure.show()


In [ ]:
delays_toc_on_toc_2023 = delays_toc_on_toc[delays_toc_on_toc.index=="Apr 2022 to Mar 2023"]
delays_toc_on_toc_2023_pie = px.pie(values=delays_toc_on_toc_2023.values[0], names=delays_toc_on_toc_2023.columns, title="Number of delays caused by TOCs to TOCs in 2023")
delays_toc_on_toc_2023_pie.show()

delays_toc_on_toc_2023_bar = px.bar(x=delays_toc_on_toc.columns,
                          y=delays_toc_on_toc_2023.values[0],
                          color=delays_toc_on_toc_2023.columns)
delays_toc_on_toc_2023_bar.update_layout(title=" Number of delay minutes caused by TOCs to TOCs in 2023",
                                  xaxis_title="TOC",
                                  yaxis_title="Number of delay minutes caused",
                                  showlegend=False,
                                  coloraxis_showscale=False)
delays_toc_on_toc_2023_bar.show()


Delays

## Delay minutes throughout the Country

In [ ]:
total_delays_nr = pd.DataFrame({"Legend": "Delays caused by NR", "x": total_delays_nr_on_toc.index, "y": total_delays_nr_on_toc.values})
total_delays_toc =  pd.DataFrame({"Legend": "Delays caused by other TOCs", "x": total_delays_toc_on_toc.index, "y": total_delays_toc_on_toc.values})
total_delays_self = pd.DataFrame({"Legend": "Delays caused by own TOC", "x": total_delays_toc_on_self.index, "y": total_delays_toc_on_self.values})
total_delays = pd.concat([total_delays_nr, total_delays_toc, total_delays_self])

total_delays_figure = px.line(total_delays, x="x", y="y", color="Legend", markers=True)
total_delays_figure.update_layout(title="Delay minutes in the Country",
                                      xaxis_title="Time period",
                                      yaxis_title="Number of delay minutess ")
total_delays_figure.show()

Delays caused by Network Rail consistently make up the majority of delays.

# Conclusions

The following parameters experienced a decline during the first year of Covid:


1.   Number of passenger journeys
2.   Distance travelled by passengers
3.   Distance travelled by trains
4.   Complaints closed
5.   Total Assist Requests
6.   Delay compensation claims closed
7.   Cancellations score
8.   Trains planned
9.  Network Rail on TOC delays
10.  TOC on self delays
11.  TOC on TOC delays



Out of these parameters, the following parameters have recovered after to pre-Covid levels:



1.   Total assist requests
2.   Delay compensation claims closed



The following got worse after Covid:

1.   Mean cancellation score has increased
2.   On time trains has worsened
3.   Trains planned will not recover to pre-covid levels



COVID did not significantly affect who were the biggest and smallest TOC's.

Less people are using trains now compared to before Covid. It will take a few more years until pre-Covid levels are met. However, with a trend of less trains planned, and rising cancellations, passengers may not experience the same levels of service they used to have.

Delays are primarily caused by Network Rail, regardless of Covid.